### ISSUE TITLE
Add an "on set" output to hb-event

### ISSUE THREAD

**Issue by hepcat72** [NorthernMan54/node-red-contrib-homebridge-automation#102]
Perhaps it's a limitation of homebridge, but I have a use-case where I want to know when a Leviton dimmer switch's off toggle is triggered even when the light it controls is already off, because I want that one switch to also be able to turn off another device.

for example, my Leviton dimmer switch controls a flood light in the Back Yard and I have a driveway flood light that it also controls when the status changes, however the Driveway Flood Light also turns on when motion is detected or I can control it using its own switch or a geofence event. That switch however is upstairs and the Leviton Switch is downstairs, so it makes it much simpler to be able to turn off the Driveway Flood Light by toggling the Off switch of the Back Yard Flood Light when I am downstairs.

However, the HB-event node does not emit anything when there's not a state change for the Leviton backyard floodlight.

The HomeKit D nodes have two outputs that I find very useful. One is "on change" and the other is "on set". Would it be possible to add such an output to the HB - event node?

**Comment by NorthernMan54** [comment]
This is already supported, try asking Siri to turn off a homebridge exposed light that is already off and see that the message is emitted.  I use this feature extensively in my automations, and with my Alexa plugin for a similar use case as yours.

hb-event subscribes to HomeKit event notification messages as per the hap spec section 6.8, so the accessory/plugin needs to emit the appropriate message for hb-event to emit the message.

**Comment by hepcat72** [comment]
Hmm. Yes, I know I can tell Siri to turn off a light that she thinks is already off and it will work, but this is not my use case.

I am polling an hb-status node for the switch every 5 seconds to catch change events when the physical wall switch is flipped/pressed. By sending a message to hb-status, if the power status has changed due to the physical switch being manipulated, the corresponding hb-event will emit an event message.

But, if I don't poll the hb-status node, I can flip the physical switch all day and the UB-event node never emits a message.

but with the polling, it only triggers hb-event to emit a message when that manipulation of the physical switch changes the power state of the light it controls. I.e. if the back yard flood light is off and I press the off button, event if I'm polling, no event is emitted from hb-event, so I have no way to have that switch turn off another device unless it's completely in synchronized power-state-wise with the back yard flood light.

Have I explained this sufficiently? I need an on-set event, but all it ever does is on-change.

I haven't tested it with Siri, so perhaps it works with Siri, but what I need is to capture physical button pressed on the physical switch. And one reason I need that to work is because my wife absolutely refuses to talk to her phone. ;)

**Comment by NorthernMan54** [comment]
I’m wondering if the Leviton plugin does not support the event interface?

One quick test is to open the home app to the room with the switch, then turn the switch on/off and the home app should update in sync with the physical switch.  If it doesn’t, then this is the issue.

**Comment by hepcat72** [comment]
Yes, if I watch the virtual button in the Home app, it updates it's state - BUT it is only updating because I set up the polling. There can be up to a 5 second delay. It's the same issue with my 2 Sonoff mini r2's. I have polling nodes that send messages into their hb-status nodes too. However, the physical switches for the sonoffs ALWAYS toggle the power state. There's not separate on and off buttons like with the Leviton. The Leviton has an on button and an off button. If the Leviton is off and I press off, there's no hb-event message emitted.

**Comment by hepcat72** [comment]
The Leviton dimmer switch model number is DW6HD by the way.

So are you suggesting that Physical switch button presses should cause an hb-event message regardless of whether that button press changes the power state or not? Is that with or without sending a polling message into an hb-status node?

I've been wondering if there's a way to get my 2 Sonoff mini r2's to make a webhook call when the physical switch is toggled because I don't like having to poll. Sonoff's DIY mode doesn't support that, but I was thinking maybe if I flashed it with tasmota, I could get it to work...

**Comment by NorthernMan54** [comment]
Staying on the Leviton

if you have to poll to get status changes then the plugin does not support events, and should be discussed with the plugin author.  The device api may not support an event driven approach so you may be out of luck, but worth discussing.

I’m not familiar with your Leviton device, but if the button press generates a event notification that is handled by HomeKit then hb-event will emit a message.  So I can’t say 100% it will work or not, but if an event notification is generated a message will be emitted.

Please keep in mind the homebridge-automation uses the HomeKit api and not homebridge internal api’s like onset.

for tasmota, with my tasmota devices and with my plugin, state changes ie button presses are immediately reflected in the home app, and hb-event will emit a message. So your good to try that out.

**Comment by hepcat72** [comment]
Does pressing off when it's already off really constitute a state change? The JSON I get out of hb-event is:

```
{
    "On": true/false,
    "Brightness": 0-100,
}
```

"On" is the current power state, so what would be emitted when none of that data is different?  Say I wanted to do something different when payload.Set == payload.On, or specifically when they differ?  I definitely have a number of uses of those 2 outputs of homekitd nodes.

Perhaps there's still a feature to be added here.

**Comment by hepcat72** [comment]
Caveat: I don't know what the JSON may look like if my Leviton Dimmer Switch was identified as a switch instead of a lightbulb.

One example of the utility of having separate onSet and onChange outputs, the following is my primary use case that uses both outputs:

For my driveway flood light, which can be turned on by motion detection and off 10 minutes after turning on:
- onChange: Send myself an SMS notifying me that the motion sensing light turned on or off
- onSet: If turning on, send a message to a deadman switch set to 10 minutes.  Every motion detection resets the timer on that deadman switch.  After 10 minutes of not receiving a message, the deadman switch sends a message to turn off the flood light

Incidentally, I did create a corresponding issue on `homebridge-leviton`:

https://github.com/tabrindle/homebridge-leviton/issues/23

**Comment by NorthernMan54** [comment]
1. I saw your issue posted against the Leviton plugin, and use case we are discussing is

_open the home app, to the room with a Leviton device.  Physically turn the switch on, and the home app is not updating in almost real time like other devices._

are you seeing that issue without your polling running?  If yes, then please update/change the Leviton issue to reflect this use case.

2. OnSet and OnChange are not part of the interface I’m using.  The interface I’m working with is the HomeKit accessory protocol, google it.

3. in HomeKit lights and switches are identical, with the only difference being what icon is used in the home app.  If you look in the home app, you can change a switch to a light or fan.

4. let’s talk about your use case further

In my version of your use case I’m using Siri and Alexa as a control for my lights, and when using Siri/Alexa to control the lights they are not aware of the light state so they always send an on or off command to homebridge to turn the device on or off respectively.  Using the hb-event node you can receive these messages and trigger further actions from them.  In my stateful lights example using the hb-resume node, I use the feature to enable 2 levels of off, the first being resume the previous state, and the second being off.

For your use case it is going to depend on how the physical switch behaves when you turn off an already off device.  Based on what your saying the Leviton switches tell homebridge that the off button was pressed on a already turned off device.  Do you have a log showing this behavior?

In regards to Tasmota devices, I’m not sure what their behavior is in that scenario, but as the buttons and relays are treated separately in most of the devices ( tuya devices might be a special use case ), triggering an action on a button is more than likely feasible with a bit of configuration tweaking.

**Comment by hepcat72** [comment]
> 1. I saw your issue posted against the Leviton plugin, and use case we are discussing is
> 
> _open the home app, to the room with a Leviton device. Physically turn the switch on, and the home app is not updating in almost real time like other devices._
> 
> are you seeing that issue without your polling running? If yes, then please update/change the Leviton issue to reflect this use case.

I'm a little unclear on the distinction you're making between the use-case I posted on that issue and the use case you mention above.

Let me back up and map out all the differences...  There are a number of ways to turn the leviton switch on.  I would have to disable my polling and perform tests for each control mechanism, but I'm fairly certain that the only things that update the home button state appearance are commands to Siri, virtual button presses in the home app, and messages sent into the hb-control node.  I don't think the other means change the home button state.  Those means are:

- Siri
   - Spoken command
- Home app
   - Virtual Button
   - Scene
   - Automation
- `node-red-contrib-homebridge-automation` in `node-red`
   - Send a message into the hb-control node (e.g. via an inject node or anything else, like motion sensing, geofence, webhook, whatever)
- In the Leviton app
   - Virtual button
   - Schedule
- `my.leviton.com`
   - Virtual Button
   - Schedule
- Physical Leviton switch

In all of these cases, these are the following ways states are observed:

- Siri
   - Ask if the lights are on
- Home app
   - Virtual button appearance
- `node-red-contrib-homebridge-automation` in `node-red`
   - Send a message into the hb-status node
- In the Leviton app
   - Virtual button appearance
- `my.leviton.com`
   - Virtual button appearance
- Physical Leviton switch
   - Indicator light on the switch

The Leviton app, my.leviton.com, and the physical switch are always in synch with one another state-wise, but they can disagree with all the other presented states (Siri, Home, and hb) but they never disagree with the actual light.  Siri and Home are always in synch together and I suspect they are also always in synch with hb, but they collectively can differ with Leviton.

There are 3 states that can exist when a command is issued:

- Command (target) state is on/off
- Actual device state is on/off (which is always accurate in the Levinton app/website/switch-indicator)
- State Home/Siri/hb thinks the device is in

You have pointed out that the command always works to *change* the actual device state regardless of any stale state.  That covers these cases:

- (command state != actual device state) and (command state != home/siri/hb state)
- (command state != actual device state) and (command state == home/siri/hb state)

In the above cases, hb-event emits a message.  But it does not account for these states:

- (command state == actual device state) and (command state != home/siri/hb state)
- (command state == actual device state) and (command state == home/siri/hb state)

In these latter cases, there is never an event emitted from hb-event, because there's no actual state change.

I don't know if Leviton or the Home app have anything they *could* do if an on switch is turned on (or off/off).  I haven't tried that in the Home app, and I only have 1 Leviton device.  But node-red could definitely do something if an on switch is turned on or vice versa.

> 2. OnSet and OnChange are not part of the interface I’m using.  The interface I’m working with is the HomeKit accessory protocol, google it.

I don't doubt that at all.  I fully expect what I want is either not possible at all or is not possible with my specific device or software.  I'm just trying to determine conclusively, which is the case.

> 3. in HomeKit lights and switches are identical, with the only difference being what icon is used in the home app.  If you look in the home app, you can change a switch to a light or fan.

I was wondering about that.

> 4. let’s talk about your use case further
> 
> In my version of your use case I’m using Siri and Alexa as a control for my lights, and when using Siri/Alexa to control the lights they are not aware of the light state so they always send an on or off command to homebridge to turn the device on or off respectively. Using the hb-event node you can receive these messages and trigger further actions from them. In my stateful lights example using the hb-resume node, I use the feature to enable 2 levels of off, the first being resume the previous state, and the second being off.
> 
> For your use case it is going to depend on how the physical switch behaves when you turn off an already off device. Based on what your saying the Leviton switches tell homebridge that the off button was pressed on a already turned off device. Do you have a log showing this behavior?

I believe this is a miscommunication.  I have never been able to make this happen with a physical switch.  I can only make it happen with a homekitd node.  Here's an example:

<img width="593" alt="image" src="https://user-images.githubusercontent.com/2300532/156648825-a2143e2d-6fbc-4bd9-aafb-67363be10206.png">

Ignore the node labels, they're unimportant.  The top output is `onChange` and the bottom is `onSet`.  The onChange is connected to a logger and an SMS node.  I used to use the onChange for everything, but I learned that sometimes, when the homekitd node state was not in synch with the device, commands weren't getting through.  I later took advantage of the difference to send myself SMS messages when the state actually changed, as opposed to the command being issued, when the nodes were always reliably in synch.

Since `homekitd` however implements everything virtually and there is no physical switch (all commands are though home/siri/node-red, perhaps all homekitd is doing is treating those state comparisons differently.  Essentially, it's doing the same exact thing hb is doing, but it's just splitting the outputs based on the previous state.  If I implemented homekitd for my leviton, I'd have to poll the switch as well to make sure the state is in synch and catch physical button presses.  So it may not be possible to catch same-state button presses.

> In regards to Tasmota devices, I’m not sure what their behavior is in that scenario, but as the buttons and relays are treated separately in most of the devices ( tuya devices might be a special use case ), triggering an action on a button is more than likely feasible with a bit of configuration tweaking.

I have 3 Sonoff S31 A15's and I do have them set to make webhook calls when their actual power state changes, so I wouldn't be surprised you could act on button press events regardless of the previous power state or whether a state change occurs or not.

**Comment by NorthernMan54** [comment]
I’m totally confused now, we started off with an issue with Leviton devices not emitting hb-event messages and are now discussing HomeKit-bridged

Please simplify the discussion and keep it crisp.  My use case from earlier is very important as it is the same interface and message that homebridge-automation hb-event node uses.  So if that use case doesn’t work in the home app, hb-event is not going to work.

**Comment by hepcat72** [comment]
Yeah. I'm going to close this. I've been looking more into it. Sorry, I know I'm not the best communicator. The Leviton switch definitely doesn't volunteer any information. Polling's the only way to get any info from it. The physical buttons, the Leviton app, the website - it doesn't push anything out. You have to poll it to get anything that happens on it.

I was trying to determine if Apple's HomeKit protocols actually supported a way to communicate button presses when there's no state change resulting from those presses. Like, could I add a request to the homebridge-Leviton api.js code to determine if a button was pressed (without a state change) and communicate that added bit of info to your node.

Leviton may or may not allow me to retrieve that info, but I learned there's no different piece of info to send. Like, right now, I can poll it and it just sends on or off.  But if I could determine button press events (like edit the homebridge-leviton api file to retrieve button press events), there's no different piece of info I can add to the communication to hb to say "my power start is on AND my on button was just pressed".

but if I could determine button presses in that api, I could simply send an "on" state. But I haven't been able to find info on the Leviton API yet.
