### ISSUE TITLE
Multiple Shelly 1PM - same name Switch 1 for all

### ISSUE THREAD

**Issue by alexwala** [NorthernMan54/node-red-contrib-homebridge-automation#105]
using [homebridge-shelly-ng](https://github.com/alexryd/homebridge-shelly-ng)
having multiple Shelly 1PM

in node-red i get multiple identical names: 'Switch 1 - Switch'

please see issue in homebridge-shelly-ng [Multiple Shelly 1PM - same name Switch 1 for all](https://github.com/alexryd/homebridge-shelly-ng/issues/47)

for test temporarily adapted Service.js `Service.prototype.toList` with:

```
    } else if (context.manufacturer === "Allterco") {
      fullName = context.name + " - " + this.name;
    }
```

**Comment by NorthernMan54** [comment]
This has been promoted as `v0.1.10` tks
