### ISSUE TITLE
Uncaught Exception / Security System

### ISSUE THREAD

**Issue by NathanAMiller** [NorthernMan54/node-red-contrib-homebridge-automation#11]
NordRed Crash:

`
2019-06-14T18:17:52.509Z hapNodeRed hbStatus received: "Arm Night - Switch" = {"characteristics":[{"aid":41,"iid":26,"value":false,"status":0}]}
14 Jun 22:47:52 - [red] Uncaught Exception:
14 Jun 22:47:52 - TypeError: Cannot read property 'homebridge' of undefined
    at /usr/lib/node_modules/hap-nodered/HAP-NodeRed.js:451:39
    at /usr/lib/node_modules/hap-nodered/HAP-NodeRed.js:669:17
    at Request.<anonymous> (/usr/lib/node_modules/hap-nodered/node_modules/hap-node-client/HAPNodeJSClient.js:406:7)
    at Request._callback (/usr/lib/node_modules/hap-nodered/node_modules/lodash/lodash.js:10052:25)
    at Request.requestRetryReply [as reply] (/usr/lib/node_modules/hap-nodered/node_modules/requestretry/index.js:105:19)
    at Request.<anonymous> (/usr/lib/node_modules/hap-nodered/node_modules/requestretry/index.js:138:10)
    at Request.self.callback (/usr/lib/node_modules/hap-nodered/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/lib/node_modules/hap-nodered/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/hap-nodered/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Unit entered failed state.
nodered.service: Failed with result 'exit-code'.
nodered.service: Service hold-off time over, scheduling restart.
Stopped Node-RED graphical event wiring tool.
Started Node-RED graphical event wiring tool.
14 Jun 22:47:55 - [info]

`

I'm using this plugin:
https://www.npmjs.com/package/homebridge-automation-switches

**Comment by NorthernMan54** [comment]
I added some logic to catch this error so it should be resolved with the latest version.

**Comment by NathanAMiller** [comment]
Thanks 🙏

I cant find the new version release here:
https://github.com/NorthernMan54/node-red-contrib-homebridge-automation/releases

How can i update to new versions ?

**Comment by NorthernMan54** [comment]
Steps are here

https://github.com/NorthernMan54/node-red-contrib-homebridge-automation#3---install-homebridge-automation-into-node-red

**Comment by NathanAMiller** [comment]
`
npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/NorthernMan54/node-red-contrib-homebridge-automation.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-18T16_54_55_626Z-debug.log

`


<img width="829" alt="Screenshot 2019-06-18 21 26 25" src="https://user-images.githubusercontent.com/51482347/59703708-bfb53780-920f-11e9-872d-1407ad18bbc4.png">

**Comment by NathanAMiller** [comment]
Log file :


`
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'https://github.com/NorthernMan54/node-red-contrib-homebridge-automation' ]
2 info using npm@6.9.0
3 info using node@v8.16.0
4 verbose npm-session 62cd94a2822397b5
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for git+https://github.com/NorthernMan54/node-red-contrib-homebridge-automation.git Error while executing:
7 silly fetchPackageMetaData undefined ls-remote -h -t https://github.com/NorthernMan54/node-red-contrib-homebridge-automation.git
7 silly fetchPackageMetaData
7 silly fetchPackageMetaData
7 silly fetchPackageMetaData spawn git ENOENT
8 timing stage:rollbackFailedOptional Completed in 4ms
9 timing stage:runTopLevelLifecycles Completed in 296ms
10 verbose stack Error: spawn git ENOENT
10 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
10 verbose stack     at onErrorNT (internal/child_process.js:362:16)
10 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:139:11)
10 verbose stack     at process._tickCallback (internal/process/next_tick.js:181:9)
11 verbose cwd /home/pi/.node-red
12 verbose Linux 4.19.42-v7+
13 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "https://github.com/NorthernMan54/node-red-contrib-homebridge-automation"
14 verbose node v8.16.0
15 verbose npm  v6.9.0
16 error path git
17 error code ENOENT
18 error errno ENOENT
19 error syscall spawn git
20 error enoent Error while executing:
20 error enoent undefined ls-remote -h -t https://github.com/NorthernMan54/node-red-contrib-homebridge-automation.git
20 error enoent
20 error enoent
20 error enoent spawn git ENOENT
21 error enoent This is related to npm not being able to find a file.
22 verbose exit [ 1, true ]`

**Comment by NorthernMan54** [comment]
Try this instead

npm install -g hap-nodered

**Comment by NathanAMiller** [comment]
It works. Thank you.

Also, It didn't crash since I updated to latest version
