### ISSUE TITLE
msg gets overwritten

### ISSUE THREAD

**Issue by bakman2** [NorthernMan54/node-red-contrib-homebridge-automation#113]
The `hb-status` node (not sure about the others) overwrites the full `msg`. 

If one wants to use the node within a flow, it will lose all existing properties, which means you cannot use it within a flow that rely on existing properties, like for example the http-in/response nodes that require the msg.res and msg.req properties to produce output.  

Request: keep existing properties and do not overwrite as it defeats the purpose of node-red.

**Comment by NorthernMan54** [comment]
Tks for reporting this, it is resolved with Version: 0.1.11
