### ISSUE TITLE
Plugin removed from homebridge, but still appears in NR

### ISSUE THREAD

**Issue by Lorccan** [NorthernMan54/node-red-contrib-homebridge-automation#119]
### Analysis

I have deleted the plugin simplisafe3 from homebridge, both from config-ui-x gui and at the command line. However, the accessory still appears in the accessory/service dropdown in NRCHA. I have tried removing the node from node-red, restarting, setting up a new project, re-adding the node, but the problem persists. 

### Expected Behavior

For the accessory to be no longer available in the dropdown.

### Steps To Reproduce

Install simplisafe3 in homebridge
Restart homebridge
Install NRCHA in nodered
Restart nodered
Add e.g., `hb - event` node to a flow and select Simplisafe from dropdown
Deploy
Delete flow
Uninstall simplisafe3 in homebridge
Restart homebridge
Add `hb -event` node again - Simplisafe is still there.

### Logs

```markdown
This is the most obvious part of the NR log in debug mode:


2024-10-14T10:08:01.391Z hapNodeRed hbConf.register SimpliSafe 3 - Security System
Oct 14 11:08:01 newhomebridge Node-RED[99537]: 2024-10-14T10:08:01.392Z hapNodeRed Register hb-event -> SimpliSafe 3 - Security System
Oct 14 11:08:01 newhomebridge Node-RED[99537]: 14 Oct 11:08:01 - [info] Started flows
Oct 14 11:08:01 newhomebridge Node-RED[99537]: 2024-10-14T10:08:01.393Z hapNodeRed _register homebridge0E:02:E8:87:58:3CSimpliSafeSimpliSafe 30000007E
Oct 14 11:08:01 newhomebridge Node-RED[99537]: 2024-10-14T10:08:01.404Z hapNodeRed _register SimpliSafe 3 - Security System 0E:02:E8:87:58:3C {
Oct 14 11:08:01 newhomebridge Node-RED[99537]:   characteristics: [
Oct 14 11:08:01 newhomebridge Node-RED[99537]:     { aid: 2, iid: 11, ev: true },
Oct 14 11:08:01 newhomebridge Node-RED[99537]:     { aid: 2, iid: 12, ev: true },
Oct 14 11:08:01 newhomebridge Node-RED[99537]:     { aid: 2, iid: 9, ev: true },
Oct 14 11:08:01 newhomebridge Node-RED[99537]:     { aid: 2, iid: 10, ev: true }
Oct 14 11:08:01 newhomebridge Node-RED[99537]:   ]
Oct 14 11:08:01 newhomebridge Node-RED[99537]: }
Oct 14 11:08:01 newhomebridge Node-RED[99537]: 2024-10-14T10:08:01.422Z hapNodeJSClient Homebridge auth failed, invalid PIN 692-69-550 0E:02:E8:87:58:3C {"characteristics":[{"aid":2,"iid":11,"ev":true},{"aid":2,"iid":12,"ev":true},{"aid":2,"iid":9,"ev":true},{"aid":2,"iid":10,"ev":true}]} null {"status":-70401}
```
```


### Configuration

```json
I don't believe this is relevant,
```

### Environment

- OS:             Raspberry Pi OS 'Bookworm'
- Software:   
- Node:         20.18.0
- npm:           10.8.2

### Process Supervisor

hb-service

**Comment by Lorccan** [comment]
I have no idea what eventually fixed the problem. I kept on clearing out what seemed to be superfluous files and adding and removing plugins from homebridge and doing the same thing at the command line and eventually I got to the point where I was seeing what I expected on the Node-RED side. I've concluded its an environmental problem here and not a bug!

**Comment by NorthernMan54** [comment]
Glad to hear
