### ISSUE TITLE
hb-status node errors upon inject-once after deploy/restart

### ISSUE THREAD

**Issue by hepcat72** [NorthernMan54/node-red-contrib-homebridge-automation#25]
I have a flow I put together to compare homebridge with another homekit node and I'm using the hb-status node to synchronize the 2 upon restart.  The inject node works fine when I inject manually, but I've tried up to a 10 second delay and I always get an error for each hb-status node after deploy/restart of flow/node-red.  Here's the error from one of them:

```
"Homebridge not initialized: HomebridgeCC:22:3D:E3:CE:22Default-ManufacturerAttic Air Conditioner00000049"
```

Do I need to "initialize" somehow before the first injection?

**Comment by Shaquu** [comment]
Connected with NRCHKB/node-red-contrib-homekit-bridged#144

**Comment by NorthernMan54** [comment]
@hepcat72 when node-red starts up, my node does homebridge instance discovery for 20 seconds, then initializes everything, so put a 30 second delay and you should be good.

**Comment by hepcat72** [comment]
@NorthernMan54 - that worked!

You know, I also noticed that upon deploy, the hb-event nodes all fire.  So I may not even need the inject once at all.  (I may need manual inject to handle synch issues.)

**Comment by Shaquu** [comment]
@hepcat72 in cas of any doubt feel free to open new Issue. I know that documentation is not clear sometimes and we will work on this in near future.
