### ISSUE TITLE
Issue with device.description of Tradfri lights

### ISSUE THREAD

**Issue by ahartman** [NorthernMan54/node-red-contrib-homebridge-automation#29]
I do not now is this is an issue with this package but it is certainly an issue with IKEA Tradfri white spectrum lightbulbs.
1. I tried setting the color temperature with the JSON key 'Color Temperature' and get the error: 'Color Temperature not valid, try Color Temperature', not exactly a clear message.
2. I interrogated the same lightbulb for status and observed the key 'ColorTemperature'.
3. Used that key 'ColorTemperature' and the lightbulb was happy.

**Some component is giving a wrong message but I do not know which one.**

**Additional question: is there a way to get not only the possible properties for an accessory but also the range to set a property?**

For 'color temperature' as example I have seen modules that use 'Kelvin', 'Mired', or the values 'cool, 'normal' and 'warm'. From node-red I found values for color temperature should range between 140 and 500, which are totally meaningless numbers. I found out by using 1 and 100.000 and checking the status. These numbers also go in the opposite direction as Kelvin: a higher number in node-red is warmer white which in Kelvin is a lower value.
Examples: 3000°K is 330 in node-red, 2500°K is 400.

**I hope there is a better way to find value ranges.**

<img width="1265" alt="Schermafbeelding 2019-10-29 om 08 16 12" src="https://user-images.githubusercontent.com/688316/67746343-92cb2980-fa26-11e9-96f2-7dcd8948beeb.png">

[flows.txt](https://github.com/NorthernMan54/node-red-contrib-homebridge-automation/files/3782159/flows.txt)

**Comment by NorthernMan54** [comment]
Tks for spotting that minor information issue, I had missed it when I was developing the code.  If you update to the latest, it should give the proper example.

In regards to the actual valid values, I use the Apple HAP Specification as a reference as Apple did a spectacular job of describing what each characteristic does and valid values.  To find the spec, google it, as it is freely available from Apple.
