### ISSUE TITLE
Do not understand how hb-resume is working

### ISSUE THREAD

**Issue by markus-fischbacher** [NorthernMan54/node-red-contrib-homebridge-automation#33]
@NorthernMan54 can you please explain the hb resume in another way? I unfortunately do not understand the usage. Do you have a screenshot of your sequence using hb-resume?

**Comment by NorthernMan54** [comment]
This is the best use case for hb-resume

https://github.com/NorthernMan54/node-red-contrib-homebridge-automation/wiki/Stateful-Lights

**Comment by markus-fischbacher** [comment]
@NorthernMan54 thank you!
