### ISSUE TITLE
Devices not showing up

### ISSUE THREAD

**Issue by gmum4d** [NorthernMan54/node-red-contrib-homebridge-automation#37]
Hi,  I'm new to node-red and need some help.  I have a Pi running Hoobs and installed Node red via the Hoobs terminal. I then installed this plugin.  I added the "hb-event" node and created a PIN and my home bridge devices initially showed up in the list. I then saved and deployed. but when I go back into it no devices show up anymore?  even if I delete it and try again nothing shows up and the same go's for "hb control" node.  I can try it 20 times and maybe once or twice the list populates but it never maintains it after saving.  Everything else in Hoobs is running fine and used daily with no problems.  Any ideas why I cannot get this to work?

Thanks

**Comment by NorthernMan54** [comment]
Logs from node red would help diagnosis this.
