### ISSUE TITLE
Events from Smart TV do not fire

### ISSUE THREAD

**Issue by Stephan811D** [NorthernMan54/node-red-contrib-homebridge-automation#38]
I integrated my LG smart TV to my homebridge but its not possible to see any events from the device in nodeRed: 

![Bildschirmfoto 2020-03-13 um 16 09 50](https://user-images.githubusercontent.com/37579239/76633691-66cbc300-6545-11ea-8400-5ba09c72b464.png)

my homebridge log shows every single event but no signal reaches rednode:

<img width="988" alt="Bildschirmfoto 2020-03-13 um 16 16 04" src="https://user-images.githubusercontent.com/37579239/76634061-0c7f3200-6546-11ea-82b1-411f4ccc856a.png">

any ideas?

thanks in advance!!

**Comment by NorthernMan54** [comment]
For events homebridge-automation listens to the HomeKit events.

If you run the homebridge instance with the plugin running in DEBUG mode, it will log the HomeKit events

Ie

Start homebridge in debug mode

DEBUG=* homebridge

Then collect a log fragment from when you trigger an event

**Comment by Stephan811D** [comment]
this is the log fragment after a event from the tv (triggered netflix - input source):

Mar 13 22:49:01 raspberrypi homebridge[11597]: [3/13/2020, 22:49:01] [My webOS tv] webOS - app launched, current appId: netflix
Mar 13 22:49:01 raspberrypi homebridge[11597]: Fri, 13 Mar 2020 21:49:01 GMT EventedHTTPServer [::ffff:10.0.0.39] Sending HTTP event '7.54' with data: {"characteristics":[{"aid":7,"iid":54,"value":0}]}
Mar 13 22:49:01 raspberrypi homebridge[11597]: Fri, 13 Mar 2020 21:49:01 GMT EventedHTTPServer [::ffff:10.0.0.44] Sending HTTP event '7.54' with data: {"characteristics":[{"aid":7,"iid":54,"value":0}]}
Mar 13 22:49:01 raspberrypi homebridge[11597]: 2020-03-13T21:49:01.545Z socket.io:client writing packet {"type":2,"data":["accessories-data",[{"aid":7,"iid":51,"uuid":"000000D8-0000-1000-8000-0026BB765291","type":"Television","humanType":"Television","serviceName":"My webOS tv","serviceCharacteristics":[{"aid":7,"iid":53,"uuid":"000000B0-0000-1000-8000-0026BB765291","type":"Active","serviceType":"Television","serviceName":"My webOS tv","description":"Active","value":1,"format":"uint8","perms":["pr","pw","ev"],"maxValue":1,"minValue":0,"canRead":true,"canWrite":true,"ev":true},{"aid":7,"iid":54,"uuid":"000000E7-0000-1000-8000-0026BB765291","type":"ActiveIdentifier","serviceType":"Television","serviceName":"My webOS tv","description":"Active Identifier","value":0,"format":"uint32","perms":["pr","pw","ev"],"canRead":true,"canWrite":true,"ev":true},{"aid":7,"iid":55,"uuid":"000000E3-0000-1000-8000-0026BB765291","type":"ConfiguredName","serviceType":"Television","serviceName":"My webOS tv","description":"Configured Name","value":"My webOS tv","format":"string","perms":["pr","pw","ev"],"canRead":true,"canWrite":true,"ev":true},{"aid":7,"iid":56,"uuid":"000000E8-0000-1000-8000-0026BB765291","type":"SleepDiscoveryMode","serviceType":"Television","serviceName":"My webOS tv","description":"Sleep Discovery Mode","value":1,"format":"uint8","perms":["pr","ev"],"maxValue":1,"minValue":0,"canRead":true,"canWrite":false,"ev":true},{"aid":7,"iid":57,"uuid":"000000E1-0000-1000-8000-0026BB765291","type":"RemoteKey","serviceType":"Television","serviceName":"My webOS tv","description":"Remote Key","format":"uint8","perms":["pw"],"maxValue":16,"minValue":0,"canRead":false,"canWrite":true,"ev":false},{"aid":7,"iid":58,"uuid":"000000DF-0000-1000-8000-0026BB765291","type":"PowerModeSelection","serviceType":"Television","serviceName":"My webOS tv","description":"Power Mode Selection","format":"uint8","perms":["pw"],"maxValue":1,"minValue":0,"canRead":false,"canWrite":true,"ev":false}],"accessoryInformation":{"Manufacturer":"LG Electronics Inc.","Model":"49UJ6309-ZA","Name":"My webOS t
Mar 13 22:49:01 raspberrypi homebridge[11597]: v","Serial Number":"78:5d:c8:25:29:63","Firmware Revision":"1.6.4"},"values":{"Active":1,"ActiveIdentifier":0,"ConfiguredName":"My webOS tv","SleepDiscoveryMode":1},"linked":[59,66,73,80],"instance":{"name":"Homebridge","username":"CC:22:3D:E3:CE:31","port":51826,"services":[],"connectionFailedCount":0,"ipAddress":"10.0.0.44"},"uniqueId":"6bfdba034516fe510b2ca4e693b4c518335ffa081795407a1ba002146bf43ce4"}]],"nsp":"/accessories"}
Mar 13 22:49:01 raspberrypi homebridge[11597]: 2020-03-13T21:49:01.546Z socket.io-parser encoding packet {"type":2,"data":["accessories-data",[{"aid":7,"iid":51,"uuid":"000000D8-0000-1000-8000-0026BB765291","type":"Television","humanType":"Television","serviceName":"My webOS tv","serviceCharacteristics":[{"aid":7,"iid":53,"uuid":"000000B0-0000-1000-8000-0026BB765291","type":"Active","serviceType":"Television","serviceName":"My webOS tv","description":"Active","value":1,"format":"uint8","perms":["pr","pw","ev"],"maxValue":1,"minValue":0,"canRead":true,"canWrite":true,"ev":true},{"aid":7,"iid":54,"uuid":"000000E7-0000-1000-8000-0026BB765291","type":"ActiveIdentifier","serviceType":"Television","serviceName":"My webOS tv","description":"Active Identifier","value":0,"format":"uint32","perms":["pr","pw","ev"],"canRead":true,"canWrite":true,"ev":true},{"aid":7,"iid":55,"uuid":"000000E3-0000-1000-8000-0026BB765291","type":"ConfiguredName","serviceType":"Television","serviceName":"My webOS tv","description":"Configured Name","value":"My webOS tv","format":"string","perms":["pr","pw","ev"],"canRead":true,"canWrite":true,"ev":true},{"aid":7,"iid":56,"uuid":"000000E8-0000-1000-8000-0026BB765291","type":"SleepDiscoveryMode","serviceType":"Television","serviceName":"My webOS tv","description":"Sleep Discovery Mode","value":1,"format":"uint8","perms":["pr","ev"],"maxValue":1,"minValue":0,"canRead":true,"canWrite":false,"ev":true},{"aid":7,"iid":57,"uuid":"000000E1-0000-1000-8000-0026BB765291","type":"RemoteKey","serviceType":"Television","serviceName":"My webOS tv","description":"Remote Key","format":"uint8","perms":["pw"],"maxValue":16,"minValue":0,"canRead":false,"canWrite":true,"ev":false},{"aid":7,"iid":58,"uuid":"000000DF-0000-1000-8000-0026BB765291","type":"PowerModeSelection","serviceType":"Television","serviceName":"My webOS tv","description":"Power Mode Selection","format":"uint8","perms":["pw"],"maxValue":1,"minValue":0,"canRead":false,"canWrite":true,"ev":false}],"accessoryInformation":{"Manufacturer":"LG Electronics Inc.","Model":"49UJ6309-ZA","Name":"My webOS
Mar 13 22:49:01 raspberrypi homebridge[11597]: tv","Serial Number":"78:5d:c8:25:29:63","Firmware Revision":"1.6.4"},"values":{"Active":1,"ActiveIdentifier":0,"ConfiguredName":"My webOS tv","SleepDiscoveryMode":1},"linked":[59,66,73,80],"instance":{"name":"Homebridge","username":"CC:22:3D:E3:CE:31","port":51826,"services":[],"connectionFailedCount":0,"ipAddress":"10.0.0.44"},"uniqueId":"6bfdba034516fe510b2ca4e693b4c518335ffa081795407a1ba002146bf43ce4"}]],"nsp":"/accessories"}
Mar 13 22:49:01 raspberrypi homebridge[11597]: 2020-03-13T21:49:01.547Z socket.io-parser encoded {"type":2,"data":["accessories-data",[{"aid":7,"iid":51,"uuid":"000000D8-0000-1000-8000-0026BB765291","type":"Television","humanType":"Television","serviceName":"My webOS tv","serviceCharacteristics":[{"aid":7,"iid":53,"uuid":"000000B0-0000-1000-8000-0026BB765291","type":"Active","serviceType":"Television","serviceName":"My webOS tv","description":"Active","value":1,"format":"uint8","perms":["pr","pw","ev"],"maxValue":1,"minValue":0,"canRead":true,"canWrite":true,"ev":true},{"aid":7,"iid":54,"uuid":"000000E7-0000-1000-8000-0026BB765291","type":"ActiveIdentifier","serviceType":"Television","serviceName":"My webOS tv","description":"Active Identifier","value":0,"format":"uint32","perms":["pr","pw","ev"],"canRead":true,"canWrite":true,"ev":true},{"aid":7,"iid":55,"uuid":"000000E3-0000-1000-8000-0026BB765291","type":"ConfiguredName","serviceType":"Television","serviceName":"My webOS tv","description":"Configured Name","value":"My webOS tv","format":"string","perms":["pr","pw","ev"],"canRead":true,"canWrite":true,"ev":true},{"aid":7,"iid":56,"uuid":"000000E8-0000-1000-8000-0026BB765291","type":"SleepDiscoveryMode","serviceType":"Television","serviceName":"My webOS tv","description":"Sleep Discovery Mode","value":1,"format":"uint8","perms":["pr","ev"],"maxValue":1,"minValue":0,"canRead":true,"canWrite":false,"ev":true},{"aid":7,"iid":57,"uuid":"000000E1-0000-1000-8000-0026BB765291","type":"RemoteKey","serviceType":"Television","serviceName":"My webOS tv","description":"Remote Key","format":"uint8","perms":["pw"],"maxValue":16,"minValue":0,"canRead":false,"canWrite":true,"ev":false},{"aid":7,"iid":58,"uuid":"000000DF-0000-1000-8000-0026BB765291","type":"PowerModeSelection","serviceType":"Television","serviceName":"My webOS tv","description":"Power Mode Selection","format":"uint8","perms":["pw"],"maxValue":1,"minValue":0,"canRead":false,"canWrite":true,"ev":false}],"accessoryInformation":{"Manufacturer":"LG Electronics Inc.","Model":"49UJ6309-ZA","Name":"My webOS tv","Ser
Mar 13 22:49:01 raspberrypi homebridge[11597]: ial Number":"78:5d:c8:25:29:63","Firmware Revision":"1.6.4"},"values":{"Active":1,"ActiveIdentifier":0,"ConfiguredName":"My webOS tv","SleepDiscoveryMode":1},"linked":[59,66,73,80],"instance":{"name":"Homebridge","username":"CC:22:3D:E3:CE:31","port":51826,"services":[],"connectionFailedCount":0,"ipAddress":"10.0.0.44"},"uniqueId":"6bfdba034516fe510b2ca4e693b4c518335ffa081795407a1ba002146bf43ce4"}]],"nsp":"/accessories"} as 2/accessories,["accessories-data",[{"aid":7,"iid":51,"uuid":"000000D8-0000-1000-8000-0026BB765291","type":"Television","humanType":"Television","serviceName":"My webOS tv","serviceCharacteristics":[{"aid":7,"iid":53,"uuid":"000000B0-0000-1000-8000-0026BB765291","type":"Active","serviceType":"Television","serviceName":"My webOS tv","description":"Active","value":1,"format":"uint8","perms":["pr","pw","ev"],"maxValue":1,"minValue":0,"canRead":true,"canWrite":true,"ev":true},{"aid":7,"iid":54,"uuid":"000000E7-0000-1000-8000-0026BB765291","type":"ActiveIdentifier","serviceType":"Television","serviceName":"My webOS tv","description":"Active Identifier","value":0,"format":"uint32","perms":["pr","pw","ev"],"canRead":true,"canWrite":true,"ev":true},{"aid":7,"iid":55,"uuid":"000000E3-0000-1000-8000-0026BB765291","type":"ConfiguredName","serviceType":"Television","serviceName":"My webOS tv","description":"Configured Name","value":"My webOS tv","format":"string","perms":["pr","pw","ev"],"canRead":true,"canWrite":true,"ev":true},{"aid":7,"iid":56,"uuid":"000000E8-0000-1000-8000-0026BB765291","type":"SleepDiscoveryMode","serviceType":"Television","serviceName":"My webOS tv","description":"Sleep Discovery Mode","value":1,"format":"uint8","perms":["pr","ev"],"maxValue":1,"minValue":0,"canRead":true,"canWrite":false,"ev":true},{"aid":7,"iid":57,"uuid":"000000E1-0000-1000-8000-0026BB765291","type":"RemoteKey","serviceType":"Television","serviceName":"My webOS tv","description":"Remote Key","format":"uint8","perms":["pw"],"maxValue":16,"minValue":0,"canRead":false,"canWrite":true,"ev":false},{"aid":7,"iid":58,"u
Mar 13 22:49:01 raspberrypi homebridge[11597]: uid":"000000DF-0000-1000-8000-0026BB765291","type":"PowerModeSelection","serviceType":"Television","serviceName":"My webOS tv","description":"Power Mode Selection","format":"uint8","perms":["pw"],"maxValue":1,"minValue":0,"canRead":false,"canWrite":true,"ev":false}],"accessoryInformation":{"Manufacturer":"LG Electronics Inc.","Model":"49UJ6309-ZA","Name":"My webOS tv","Serial Number":"78:5d:c8:25:29:63","Firmware Revision":"1.6.4"},"values":{"Active":1,"ActiveIdentifier":0,"ConfiguredName":"My webOS tv","SleepDiscoveryMode":1},"linked":[59,66,73,80],"instance":{"name":"Homebridge","username":"CC:22:3D:E3:CE:31","port":51826,"services":[],"connectionFailedCount":0,"ipAddress":"10.0.0.44"},"uniqueId":"6bfdba034516fe510b2ca4e693b4c518335ffa081795407a1ba002146bf43ce4"}]]
Mar 13 22:49:01 raspberrypi homebridge[11597]: 2020-03-13T21:49:01.548Z engine:socket sending packet "message" (2/accessories,["accessories-data",[{"aid":7,"iid":51,"uuid":"000000D8-0000-1000-8000-0026BB765291","type":"Television","humanType":"Television","serviceName":"My webOS tv","serviceCharacteristics":[{"aid":7,"iid":53,"uuid":"000000B0-0000-1000-8000-0026BB765291","type":"Active","serviceType":"Television","serviceName":"My webOS tv","description":"Active","value":1,"format":"uint8","perms":["pr","pw","ev"],"maxValue":1,"minValue":0,"canRead":true,"canWrite":true,"ev":true},{"aid":7,"iid":54,"uuid":"000000E7-0000-1000-8000-0026BB765291","type":"ActiveIdentifier","serviceType":"Television","serviceName":"My webOS tv","description":"Active Identifier","value":0,"format":"uint32","perms":["pr","pw","ev"],"canRead":true,"canWrite":true,"ev":true},{"aid":7,"iid":55,"uuid":"000000E3-0000-1000-8000-0026BB765291","type":"ConfiguredName","serviceType":"Television","serviceName":"My webOS tv","description":"Configured Name","value":"My webOS tv","format":"string","perms":["pr","pw","ev"],"canRead":true,"canWrite":true,"ev":true},{"aid":7,"iid":56,"uuid":"000000E8-0000-1000-8000-0026BB765291","type":"SleepDiscoveryMode","serviceType":"Television","serviceName":"My webOS tv","description":"Sleep Discovery Mode","value":1,"format":"uint8","perms":["pr","ev"],"maxValue":1,"minValue":0,"canRead":true,"canWrite":false,"ev":true},{"aid":7,"iid":57,"uuid":"000000E1-0000-1000-8000-0026BB765291","type":"RemoteKey","serviceType":"Television","serviceName":"My webOS tv","description":"Remote Key","format":"uint8","perms":["pw"],"maxValue":16,"minValue":0,"canRead":false,"canWrite":true,"ev":false},{"aid":7,"iid":58,"uuid":"000000DF-0000-1000-8000-0026BB765291","type":"PowerModeSelection","serviceType":"Television","serviceName":"My webOS tv","description":"Power Mode Selection","format":"uint8","perms":["pw"],"maxValue":1,"minValue":0,"canRead":false,"canWrite":true,"ev":false}],"accessoryInformation":{"Manufacturer":"LG Electronics Inc.","Model":"49UJ6309-ZA","Name":"My we
Mar 13 22:49:01 raspberrypi homebridge[11597]: bOS tv","Serial Number":"78:5d:c8:25:29:63","Firmware Revision":"1.6.4"},"values":{"Active":1,"ActiveIdentifier":0,"ConfiguredName":"My webOS tv","SleepDiscoveryMode":1},"linked":[59,66,73,80],"instance":{"name":"Homebridge","username":"CC:22:3D:E3:CE:31","port":51826,"services":[],"connectionFailedCount":0,"ipAddress":"10.0.0.44"},"uniqueId":"6bfdba034516fe510b2ca4e693b4c518335ffa081795407a1ba002146bf43ce4"}]])
Mar 13 22:49:01 raspberrypi homebridge[11597]: 2020-03-13T21:49:01.548Z engine:socket flushing buffer to transport
Mar 13 22:49:01 raspberrypi homebridge[11597]: 2020-03-13T21:49:01.548Z engine:ws writing "42/accessories,["accessories-data",[{"aid":7,"iid":51,"uuid":"000000D8-0000-1000-8000-0026BB765291","type":"Television","humanType":"Television","serviceName":"My webOS tv","serviceCharacteristics":[{"aid":7,"iid":53,"uuid":"000000B0-0000-1000-8000-0026BB765291","type":"Active","serviceType":"Television","serviceName":"My webOS tv","description":"Active","value":1,"format":"uint8","perms":["pr","pw","ev"],"maxValue":1,"minValue":0,"canRead":true,"canWrite":true,"ev":true},{"aid":7,"iid":54,"uuid":"000000E7-0000-1000-8000-0026BB765291","type":"ActiveIdentifier","serviceType":"Television","serviceName":"My webOS tv","description":"Active Identifier","value":0,"format":"uint32","perms":["pr","pw","ev"],"canRead":true,"canWrite":true,"ev":true},{"aid":7,"iid":55,"uuid":"000000E3-0000-1000-8000-0026BB765291","type":"ConfiguredName","serviceType":"Television","serviceName":"My webOS tv","description":"Configured Name","value":"My webOS tv","format":"string","perms":["pr","pw","ev"],"canRead":true,"canWrite":true,"ev":true},{"aid":7,"iid":56,"uuid":"000000E8-0000-1000-8000-0026BB765291","type":"SleepDiscoveryMode","serviceType":"Television","serviceName":"My webOS tv","description":"Sleep Discovery Mode","value":1,"format":"uint8","perms":["pr","ev"],"maxValue":1,"minValue":0,"canRead":true,"canWrite":false,"ev":true},{"aid":7,"iid":57,"uuid":"000000E1-0000-1000-8000-0026BB765291","type":"RemoteKey","serviceType":"Television","serviceName":"My webOS tv","description":"Remote Key","format":"uint8","perms":["pw"],"maxValue":16,"minValue":0,"canRead":false,"canWrite":true,"ev":false},{"aid":7,"iid":58,"uuid":"000000DF-0000-1000-8000-0026BB765291","type":"PowerModeSelection","serviceType":"Television","serviceName":"My webOS tv","description":"Power Mode Selection","format":"uint8","perms":["pw"],"maxValue":1,"minValue":0,"canRead":false,"canWrite":true,"ev":false}],"accessoryInformation":{"Manufacturer":"LG Electronics Inc.","Model":"49UJ6309-ZA","Name":"My webOS tv","Serial Numb
Mar 13 22:49:01 raspberrypi homebridge[11597]: er":"78:5d:c8:25:29:63","Firmware Revision":"1.6.4"},"values":{"Active":1,"ActiveIdentifier":0,"ConfiguredName":"My webOS tv","SleepDiscoveryMode":1},"linked":[59,66,73,80],"instance":{"name":"Homebridge","username":"CC:22:3D:E3:CE:31","port":51826,"services":[],"connectionFailedCount":0,"ipAddress":"10.0.0.44"},"uniqueId":"6bfdba034516fe510b2ca4e693b4c518335ffa081795407a1ba002146bf43ce4"}]]"

when i read the state of the television element i can see the identifier code:

![Bildschirmfoto 2020-03-13 um 22 56 32](https://user-images.githubusercontent.com/37579239/76662384-158bf580-657e-11ea-9277-97b394a9130f.png)

the identifier code changes when I use a different input source.

**Comment by NorthernMan54** [comment]
I need to look into this further to determine why it isn’t working with TV accessories.

Sean

**Comment by NorthernMan54** [comment]
Okay, I just ran some testing and for the change in inputs I can confirm that it works as designed.  This is with the plugin homebridge-yamaha-zone-tv.  For the node in NODE-RED I chose the "Television" device and not the "Input Source" device.  The "Input Source" node only controls visibility of the input in the home app, and allows changing the input name.  "Input Source" does not change the input, to change inputs you need to change the ActiveIdentifier characteristic that is part the "Television" node.

Here are the input change events being logged by NODE-RED

hapNodeRed hbEvent Front { host: '192.168.1.155',
  port: 59818,
  aid: 1,
  iid: 12,
  value: 2,
  status: 2 } { ConfiguredName: 'Front',
  SleepDiscoveryMode: 0,
  RemoteKey: undefined,
  CurrentMediaState: 0,
  TargetMediaState: 0,
  PictureMode: 0,
  PowerModeSelection: undefined,
  Active: 1,
  ActiveIdentifier: 3 } +22s

![Screen Shot 2020-03-24 at 6 51 57 PM](https://user-images.githubusercontent.com/19808920/77484552-34ea1480-6e01-11ea-82db-7b11abc517d3.png)

This is my test of changing inputs

![Screen Shot 2020-03-24 at 7 20 35 PM](https://user-images.githubusercontent.com/19808920/77486118-3c132180-6e05-11ea-9c56-61c6e92b15d6.png)


Looking at this further I should add some commentary around using Node-Red with a Television accessory in the README.  And provide some examples of how to change inputs etc.

**Comment by NorthernMan54** [comment]
I started collecting notes for other people who are attempting to control a TV accessory here.

https://github.com/NorthernMan54/node-red-contrib-homebridge-automation/wiki/Television-Accessory
