### ISSUE TITLE
Not finding devices

### ISSUE THREAD

**Issue by maxi8815** [NorthernMan54/node-red-contrib-homebridge-automation#39]
![image](https://user-images.githubusercontent.com/44240034/77808207-3453b700-7069-11ea-9b32-10b473790235.png)
Hey guys, I cannot se any devices from homebridge, in the image an error shows up,  con you please help me?

**Comment by NorthernMan54** [comment]
Can you share a longer log fragment, am thinking there are other errors before this.

Are all your Homebridge instances running with -I

**Comment by maxi8815** [comment]
Homebridge wasn't running with  -I  I enabled it and now there is no error in the nodered logs, but I still have problems, because no device shows up.

In the screenshoot you can see the whole log from nodered start
![image](https://user-images.githubusercontent.com/44240034/77808888-03c14c80-706c-11ea-8a44-176843302066.png)

As you can see the device list is empty:

![image](https://user-images.githubusercontent.com/44240034/77808904-1a67a380-706c-11ea-9a37-5937d6e099d2.png)

Homebridge Config:
![image](https://user-images.githubusercontent.com/44240034/77808937-3cf9bc80-706c-11ea-95d1-2d676dc70106.png)


Thanks in advance.

**Comment by NorthernMan54** [comment]
Have you tried the refresh option button to the right of device?

**Comment by maxi8815** [comment]
I have tried, but nothing happens :(

**Comment by NorthernMan54** [comment]
Can you start node-red with DEBUG enabled?  

ie

`DEBUG=*,-puppeteer:*,-express:*,-body-parser:*,-send node-red`

And share the log

**Comment by maxi8815** [comment]
I have enabled logs:
![image](https://user-images.githubusercontent.com/44240034/77810787-2c017900-7075-11ea-951d-bc41ca32e4a3.png)


No news in the nodered log:
![image](https://user-images.githubusercontent.com/44240034/77810769-10966e00-7075-11ea-9017-3b1c5deca4c3.png)

**Comment by NorthernMan54** [comment]
Sorry am not familiar with your runtime environment

Debug logs typically look like this

DEBUG=*,-puppeteer:*,-express:*,-body-parser:*,-send npm/bin/node-red
  oauth2orize register exchanger password password +0ms
27 Mar 20:53:37 - [info] 

Welcome to Node-RED
===================

27 Mar 20:53:37 - [info] Node-RED version: v1.0.2
27 Mar 20:53:37 - [info] Node.js  version: v10.15.3
27 Mar 20:53:37 - [info] Darwin 18.7.0 x64 LE
27 Mar 20:53:37 - [info] Loading palette nodes
  NRCHKB RED settings available +0ms
  NRCHKB Initialize AccessoryAPI +0ms
  NRCHKB Initialize ServiceAPI +1ms
27 Mar 20:53:40 - [info] Settings file  : /Users/sgracey/.node-red/settings.js
27 Mar 20:53:40 - [info] Context store  : 'default' [module=memory]
27 Mar 20:53:40 - [info] User directory : /Users/sgracey/.node-red
27 Mar 20:53:40 - [warn] Projects disabled : editorTheme.projects.enabled=false
27 Mar 20:53:40 - [info] Flows file     : /Users/sgracey/.node-red/flows_Heisenberg.local.json
27 Mar 20:53:40 - [warn] 

---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.

If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.

You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------

27 Mar 20:53:40 - [info] Starting flows
  hapNodeJSClient Starting Homebridge instance discovery +0ms
  hapNodeRed hbConf.register Bunkie - Switch +0ms
  hapNodeRed Register hb-event -> Bunkie - Switch +0ms
27 Mar 20:53:40 - [info] Started flows
27 Mar 20:53:40 - [info] Server now running at http://127.0.0.1:1880/
  hapNodeJSClient HAP Device discovered Raj-Other [ '192.168.1.10', 'fe80::706f:fb71:9a33:b6ae' ] +512ms
  hapNodeJSClient HAP instance address: Raj-Other -> CC_22_3D_E3_CF_34.local -> 192.168.1.10:51828 +4ms
  hapNodeJSClient HAP Device discovered Raj-Yamaha [ '192.168.1.10', 'fe80::706f:fb71:9a33:b6ae' ] +9ms
  hapNodeJSClient HAP instance address: Raj-Yamaha -> BC_22_3D_E3_CF_46.local -> 192.168.1.10:51831 +1ms
  hapNodeJSClient HAP Device discovered Bunkie [ '192.168.1.10', 'fe80::706f:fb71:9a33:b6ae' ] +1ms
  hapNodeJSClient HAP instance address: Bunkie -> B9_3E_63_12_58_DE.local -> 192.168.1.10:45889 +0ms
  hapNodeJSClient HAP Device discovered Cottage Porch [ '192.168.1.10', 'fe80::706f:fb71:9a33:b6ae' ] +1ms
  hapNodeJSClient HAP instance address: Cottage Porch -> 59_55_95_A1_3F_68.local -> 192.168.1.10:36447 +0ms
  hapNodeJSClient HAP Device discovered Raj-Camera [ '192.168.1.10', 'fe80::706f:fb71:9a33:b6ae' ] +0ms
  hapNodeJSClient HAP instance address: Raj-Camera -> CC_22_3D_E3_CF_35.local -> 192.168.1.10:51829 +0ms
  hapNodeJSClient Homebridge instance discovered Raj-Other-5019 with 12 accessories +51ms
  hapNodeJSClient Homebridge instance discovered Raj-Yamaha-C2C1 with 5 accessories +1ms
  hapNodeJSClient Homebridge instance discovered Bunkie-3A49 with 1 accessories +44ms
  hapNodeJSClient Homebridge instance discovered Cottage Porch-6CE1 with 1 accessories +1ms
  hapNodeJSClient Homebridge instance discovered Raj-Camera-B7A1 with 13 accessories +3ms
  hapNodeJSClient HAP Device discovered Raj-Hue [ '192.168.1.10', 'fe80::706f:fb71:9a33:b6ae' ] +188ms
  hapNodeJSClient HAP instance address: Raj-Hue -> CC_22_3D_E3_CF_33.local -> 192.168.1.10:51827 +1ms
  hapNodeJSClient Homebridge instance discovered Raj-Hue-B509 with 6 accessories +18ms
  hapNodeJSClient HAP Device discovered Raj-NodeRed [ '192.168.1.10', 'fe80::706f:fb71:9a33:b6ae' ] +288ms
  hapNodeJSClient HAP instance address: Raj-NodeRed -> 00_69_62_b7_ae_38_d4_28.local -> 192.168.1.10:51830 +0ms
  hapNodeJSClient Homebridge instance discovered Raj-NodeRed-3C2A with 11 accessories +23ms
  hapNodeJSClient HAP Device discovered Raj [ '192.168.1.10', 'fe80::706f:fb71:9a33:b6ae' ] +592ms
  hapNodeJSClient HAP instance address: Raj -> BC_22_3D_E3_CF_32.local -> 192.168.1.10:51826 +0ms
  hapNodeJSClient Homebridge instance discovered Raj-A131 with 22 accessories +53ms
  hapNodeJSClient Ending Homebridge instance discovery +18s
  Service Missing HB Type 49FB9D4D +0ms
  Service Missing HB Type 49FB9D4D +1ms
  Service Missing HB Type 00000110 +1ms
  Service Missing HB Type 00000110 +1ms
  Service Missing HB Type 00000110 +0ms
  Service Missing HB Type 00000110 +1ms
  Service Missing HB Type 49FB9D4D +0ms
  Service Missing HB Type E863F007 +0ms
  Service Missing HB Type 49FB9D4D +1ms
  Service Missing HB Type 00000012 +1ms
  Service Missing HB Type 49FB9D4D +1ms
  Service Missing HB Type E863F007 +0ms
  Service Missing HB Type E863F007 +0ms
  Service Missing HB Type E863F007 +0ms
  Service Missing HB Type E863F007 +0ms
  Service Missing HB Type E863F007 +1ms
  Service Missing HB Type E863F007 +0ms
  Service Missing HB Type E863F007 +0ms
  Service Missing HB Type E863F007 +0ms
  Service Missing HB Type E863F007 +1ms
  Service Missing HB Type E863F007 +0ms
  hapNodeRed Discovered 86 new evDevices +20s
  hapNodeRed Discovered 66 new ctDevices +4ms
  hapNodeRed hb-event registered: Bunkie - Switch -> 192.168.1.10:45889 {"characteristics":[{"aid":1,"iid":26,"status":0}]} +27ms
  hapNodeRed hbEvent.register Bunkie - Switch +2ms
  hapNodeRed _status request: Bunkie - Switch -> 192.168.1.10:45889 -> ?id=1.26 +9ms
  hapNodeRed hbEvent received: Bunkie - Switch = [{"aid":1,"iid":26,"value":false,"status":0}] { On: false } +26ms

**Comment by maxi8815** [comment]
Ok I Fixed it! It was a problem with Docker networking. Thank you for your support!

**Comment by NorthernMan54** [comment]
Tks

**Comment by Shukuyen** [comment]
@maxi8815 I might have the same issue. Do you still remember what you Docker networking issue was and how you fixed it? Thanks in advance and sorry for warming up this super old thread :)
