### ISSUE TITLE
homebridge is not running in insecure mode with -I

### ISSUE THREAD

**Issue by Nastras** [NorthernMan54/node-red-contrib-homebridge-automation#43]
Hello @NorthernMan54 ,

after the update from homebridge to v1.0.0 my homebridge instances are no longer accessible in node-red-contrib-homebridge-automation. In the log I get the following error:

Apr 27 09:16:11 SHS Node-RED[3661]: 2020-04-27T07:16:11.220Z hapNodeJSClient HAP Discover failed nodered-dummy instance http://192.168.178.11:36087 invalid PIN or homebridge is not running in insecure mode with -I

The Homebridge-option file is unchanged and the value -I is set.
HOMEBRIDGE_OPTS=-I -C -T -Q -U /var/homebridge-hue

do you have an idea?

Thank you!

**Comment by NorthernMan54** [comment]
Please update to the latest version of node-red-contrib-homebridge-automation and try again.  A couple of changes were needed to support v1.0.0 of homebridge.

**Comment by b2un0** [comment]
we can't upgrade because 0.0.59 is listed here
https://flows.nodered.org/node/node-red-contrib-homebridge-automation

**Comment by b2un0** [comment]
My Node-RED installation does not offer me the new Version.
Within Docker, i must use the the build in pallete manager which stuck on 0.0.59

![2020-04-27 at 17 14](https://user-images.githubusercontent.com/2155498/80388813-a0188200-88aa-11ea-87d9-dccc2c830c5c.png)

also a container restart does not work (currently the container restarts every ~30 seconds through the outdated homebridge plugin)..

https://hub.docker.com/r/nodered/node-red

**Comment by Nastras** [comment]
I have done the update now, unfortunately the problem still exists?
After the update I restarted node-red.

![9F109FE2-C060-4467-B53D-0102B8768B89](https://user-images.githubusercontent.com/27686185/80391847-97c24600-88ae-11ea-98f5-316d321d735d.jpeg)

![2B93D2E3-5287-4659-BBF7-A6581A16DDEE](https://user-images.githubusercontent.com/27686185/80391936-b9233200-88ae-11ea-973d-c7b91b7ab67c.jpeg)

**Comment by Nastras** [comment]
Just noticed that it has not loaded in node-red but not even after a reboot.

![BD607AFB-954D-42F8-A462-DAD06C085C27](https://user-images.githubusercontent.com/27686185/80393209-76625980-88b0-11ea-9493-a52388dba6e3.jpeg)

**Comment by NorthernMan54** [comment]
Look at the error message in detail, those appear to coming from node-red and not Homebridge.  Are you using HomeKit-bridged in Node-Red?

**Comment by Nastras** [comment]
> Are you using HomeKit-bridged in Node-Red?

Yes

**Comment by NorthernMan54** [comment]
There is a setting in HomeKit-bridged to allow insecure access

But with that said homebridge-automation should be working for you.

**Comment by Nastras** [comment]
Sorry for the late reply. It's working again now. Thanks a lot!
