### ISSUE TITLE
Automate light using homebridge-automation-calendar

### ISSUE THREAD

**Issue by frieck** [NorthernMan54/node-red-contrib-homebridge-automation#46]
Hi,
I am struggling to make an automation so I can call a scene (or a custom switch) that will turn on some things on my living room, and if necessary (if it is night or during sunset) some lights on.
The deal is to do that conditionally. 
I have already added Homebridge Automation Calendar to my homebridge and was trying to use it as the source to know the day time.

I just cannot use it, if I add it to my flow, it reports nothing....

Am I doing something wrong?
Can you guys help me?

Thanks,
Felipe

**Comment by NorthernMan54** [comment]
I looked at that plugin, and it only generates events once an hour, so it is unlikely to do what you want.

https://github.com/paolotremadio/homebridge-automation-calendar/blob/dcddd59b4d0f05e65a7577b5d4747cf0b0662e21/index.js#L124

What about just using the a Home App automation to trigger a dummy switch created with homekit-bridged node ?

Or this node-red native node

https://www.npmjs.com/package/node-red-contrib-bigtimer
