### ISSUE TITLE
NodeRed restarts due to some bug

### ISSUE THREAD

**Issue by MatsA** [NorthernMan54/node-red-contrib-homebridge-automation#48]
Thanks for a nice plugin !
Have used Your node in the latest Hoobs install and it worked very well. 
But now testing I have got an issue on a fresh RPi 3, Buster Lite, install with the latest Homebridge 1.1.0, Node v12.16.3, please check log.
[HB_log.txt](https://github.com/NorthernMan54/node-red-contrib-homebridge-automation/files/4655838/HB_log.txt)
Any ideas ?

**Comment by NorthernMan54** [comment]
Please update to the latest version and try again.

Tks goes to @dxdc for identifying the fix

**Comment by MatsA** [comment]
Thanks for quick response !
Did a `npm install node-red-contrib-homebridge-automation` NodeRed doesn't restart but instead homebridge never starts, even after uninstalling Your Node ??
[HB2.txt](https://github.com/NorthernMan54/node-red-contrib-homebridge-automation/files/4659565/HB2.txt)

**Comment by NorthernMan54** [comment]
Those logs while being interesting don’t actually show what is going on.

**Comment by MatsA** [comment]
Ok, so how can I help ? A complete log from after a restart ?

**Comment by NorthernMan54** [comment]
A log file showing the error is the best.  Including the details around the outage

**Comment by MatsA** [comment]
Hi ! Did a fresh install and it seems that the homebridge server can't handle an service install with 
`sudo hb-service install --port 80 --user pi` 
so no blame on You ! Thanks !
