### ISSUE TITLE
Issue with PIN (hap-node-client)

### ISSUE THREAD

**Issue by dxdc** [NorthernMan54/node-red-contrib-homebridge-automation#49]
I have two homebridge instances running on the same machine with different PIN#'s.

On my second hb instance, whenever calling any items from NR, I get this message (presumably from HAPNodeJSClient.js). Note, these are the same IP address, just a different PIN#.

`"192.168.XX.XXX:XXXX -> Error: Homebridge auth failed, invalid PIN undefined -> undefined"`

Also, have noticed that the list of accessories is also fully populated regardless of which PIN# I choose in the list, I see all the items (from all PIN#).

**Comment by dxdc** [comment]
Cross-referencing #36 here

**Comment by dxdc** [comment]
I isolated the issue, but didn't fix it in the cleanest way for now. The issue is actually with `HAPNodeJSClient.js`.

The problem is that `this.pin` is set to the default instead of the actual pin. I didn't determine yet if that is due to the wrong pin# being provided or maybe options['pin'] is just undefined.

`this.pin = options['pin'] || '031-45-154';`

I verified that the pin specified in "authorization" was indeed the wrong pin by inspecting `response`. As a simple workaround for now, I replaced this code:

```js
  request({
    eventBus: this._eventBus,
    method: 'PUT',
    url: 'http://' + ipAddress + ':' + port + '/characteristics',
    timeout: this.reqTimeout,
    maxAttempts: 1, // (default) try 5 times
    headers: {
      "Content-Type": "Application/json",
      "authorization": this.pin,
      "connection": "keep-alive"
    },
    body: body
  }, function(err, response) {
```

`"authorization": this.pin,`
with:
`"authorization": (port == '12345') ? '031-45-999' : this.pin,`
(or `instance.port` as appropriate)

in all places in the code.

So, at least it's a starting place of the problem - because the correct pin# is not being supplied. If I learn anything else I'll update this thread.

**Comment by NorthernMan54** [comment]
Homebridge ( HAP-NodeJS ) don't validate the PIN when asked for the list of accessories, so when the Homebridge-automation instance discovery process happens it will populate the list from every Homebridge instance running in in-secure mode.   Causing your original issue.  I raised this with the homebridge back end team, and it was not felt to be a big issue so wasn't fixed.

For me, with devices I don't want exposed I just don't run homebridge with -I.

But what does happen occasionally is that my test setup leaks into my production setup causing minor issues.   So I try to manage thru device naming ( ie Test - Thermostat ), and only running in in-secure mode for limited time.

PS I have a Reno planned for this code base, as I have changed how Hap-Node-Client maintains the relationship with each homebridge instance from the current host:port usage to homebridge instance name.  This is to fix an issue with host and port changing after a reboot.   The change is currently in a beta I'm running with homebridge-alexa and once it is shipped, I will pivot to this code base.   This is the ByDeviceID interface I added to Hap-Node-Client last month

**Comment by dxdc** [comment]
> Homebridge ( HAP-NodeJS ) don't validate the PIN when asked for the list of accessories, so when the Homebridge-automation instance discovery process happens it will populate the list from every Homebridge instance running in in-secure mode.

Ah, ok, this makes sense @NorthernMan54.

Regarding the "invalid PIN undefined" message, I fixed this with a PR: https://github.com/NorthernMan54/Hap-Node-Client/pull/30/files (`bind` was missing).

I realized a more fundamental problem though. There is no support for different PIN#'s on hb instances.

Consider:
```js
    if (!homebridge) {
      homebridge = new HAPNodeJSClient({
        "pin": n.username,
        "refresh": 900,
        "debug": true,
        "timeout": 20,
        "reqTimeout": 7000
      });
```

This just creates a single, global HAPNodeJSClient per instance, but using the same pin for each! I created 2 PRs that refactor these calls to support multiple PINs. In thinking about this, really, pin shouldn't be used as some kind of global parameter because we can't know the PIN# from mdns discovery and so there doesn't seem to be a convenient way to map PIN# to Nodes. They should just be assigned manually in that case.

These two PR's fix these issues:

- https://github.com/NorthernMan54/node-red-contrib-homebridge-automation/pull/50
- https://github.com/NorthernMan54/Hap-Node-Client/pull/31

> PS I have a Reno planned for this code base, as I have changed how Hap-Node-Client maintains the relationship with each homebridge instance from the current host:port usage to homebridge instance name.

Great news. I think it will be much smoother to use deviceId instead of IP, although honestly I never have these issues with IP addresses moving around. In my opinion for any kind of home automation, reserved IPs are critical.

**Comment by pedroxns** [comment]
Hello, same auth issue here !
Trying to make node-red activate a lamp (testing with lamps to do more latter) but keep getting the message: 
"192.168.0.73:51121 -> Error: Homebridge auth failed, invalid PIN 68821899 -> undefined"

My homebridge is running on a rPi4 with the local ip above and my node-red instance is running alone on a rPizero in 192.168.0.42.

I'm testing the Zero to use with an anemometer to make a wind-speed trigger to retract an awning, in the future Homebridge and Node-red will be on the same device.

**Comment by NorthernMan54** [comment]
@pedroxns please open a new issue for your problem and include more details.

**Comment by pedroxns** [comment]
Hey, thanks for your reply !
Just rebooted everything e it's working !

**Comment by dxdc** [comment]
@NorthernMan54 did you still want to close this? The issue still persists. I think @pedroxns 's issue was different.

**Comment by NorthernMan54** [comment]
I was closing due to the noise factor
