### ISSUE TITLE
Beta Test for Version 0.1.0

### ISSUE THREAD

**Issue by NorthernMan54** [NorthernMan54/node-red-contrib-homebridge-automation#54]
### Functional Improvement for long standing issues

* [ ] Switch from host:port to deviceid for homebridge instances
* [ ] Enable multiple pins #49 
* [ ] Update hap-nodeclient to use promises instead of callbacks
* [x] Create beta branch and NPM publish scripts
* [ ] Switch to axios instead of requests
* [x] For node.timeout (used to set status) add a clearTimeout

### New Features

* [ ] Improve the device selection process. #34 

### Housekeeping

* [ ] Create Changelog.MD

### To install the beta version, please use this command

```
cd .node-red
npm install homebridge-automation@beta
```

### To rollback to the production version please use

```
cd .node-red
npm install homebridge-automation@latest
```

**Comment by NorthernMan54** [comment]
@dxdc What else is on the list?

**Comment by dxdc** [comment]
this looks great @NorthernMan54! A few other ideas?

1. Switching to `axios` instead of `requests` since it's deprecated? Wondering if it will be more stable as well.
2. Also, for `node.timeout` (used to set status) maybe add a clearTimeout b/c just reassigning it doesn't necessarily clear the existing one.

**Comment by gewaechshaus** [comment]
Hey @NorthernMan54,

correct me if I am wrong, but I think you have posted wrong install instructions... (In case of running node-red on a pi/buster)

Change 
`npm install homebridge-automation@beta`

To
`npm install node-red-contrib-homebridge-automation@beta`

Cheers
Jan

**Comment by NorthernMan54** [comment]
@gewaechshaus You are are correct, typo in that.  Also as a FYI, I got distracted with other things and have not used the BETA for anything yet.  The master branch is the most recent code base.

**Comment by Keesromkes** [comment]
@NorthernMan54 expecting any new betas?

**Comment by NorthernMan54** [comment]
Actually I have not been focused on this recently, been playing with esp32/esp8266 devices receiving and sending 433mhz signals lately

**Comment by dxdc** [comment]
@NorthernMan54 As far as sending signals, this product is excellent:

https://bondhome.io/

They have a local API, totally extensible, as well as an iPhone app. Receiving signals is another story though... although I have some good experience with rtl_433 (SDR library) which is a fun way to do it.

**Comment by NorthernMan54** [comment]
I had been using sdr’s connected to a RPI ( homebridge-rtl ) but have are looking to improve my deployment and use an esp8266

this is one device im building, esp8266 with RXB6 running RFLink

![71858C06-F65D-492F-BDBB-38DCDD417B0F](https://user-images.githubusercontent.com/19808920/104373860-043dad80-54ef-11eb-9152-55245e07ed5d.jpeg)

**Comment by dxdc** [comment]
Nice! I have some ESP8266 also (is that a nodeMCU?), but it looked fairly tricky to program the Rf module... and I didn't have much luck with it. I had not seen RFLink! That looks really interesting, seems like a better type of SDR then and more energy efficient?

Would be very curious what that looks like. I have some ESP8266 code I can share too that I used to create a simple webserver and have some experience with SPIFFS too for storage. Ultimately, hooking this to MQTT for bidirectional communication would be amazing.

**Comment by NorthernMan54** [comment]
Thanks for offering to share your code.

I have been focused on leveraging other people's frameworks and just submitting pull requests to add any features I need.   Am currently looking at [openmqttgateway](https://docs.openmqttgateway.com).  I found rolling my own package from scratch not really worth the effort.

**Comment by dxdc** [comment]
@NorthernMan54 openmqttgateway reminds me of Tasmota, though I think Tasmota may be more full featured (possibly more so than you'd need)? I've had a lot of success with that.

https://tasmota.github.io/

The rules engine in Tasmota is exceptional though. You can have it take specific actions after power cycle, etc.

**Comment by NorthernMan54** [comment]
Two thumbs up on Tasmota ( I flashed my fleet of random purchases and device creations over the years to Tasmota during the summer ).  And created a plugin [Homebridge-tasmota](https://github.com/NorthernMan54/homebridge-tasmota) to simplify management.   After seeing how feature rich it was, I have stopped playing around with random code.

Unfortunately though for my use case, Hampton Bay Ceiling Fans, GE Ceiling Fans and random 433Mhz sensors Tasmota doesn't work.  My V2 Device ( ESP8266 and CC1101 ) is starting to look promising with OpenMQTTGateway.

What I'm looking to create is a transmitter module for 303Mhz, 315Mhz and receiver for 433Mhz.  And also IR.  Only I complete design looking at a mini production run of 3 units ( 2 for me and one for a buddy ).  If it looks like I'm jumping around a bit, in early December I had started using the RXB6 module, and at the same time ordered a CC1101 with a 6 week delivery.  It showed up earlier this week, and after hooking it up, I went wow, this is night and day better than the RXB6 approach and hence parked it.

This is an ESP32 connected to a CC1101 Module running openmqttgateway

![IMG_5831](https://user-images.githubusercontent.com/19808920/104818875-39504580-57f8-11eb-94ee-93308cdaafb8.jpg)

**Comment by dxdc** [comment]
This looks really interesting! I'm curious how your production goes with it.

You've seen the ceiling fan replacements though w/ Sonoff (can be flashed w/ Tasmota)?
https://sonoff.tech/product/wifi-diy-smart-switches/ifan03

Those would work to replace the controllers in your fans, but seems like your use cases may be different. Rf is king in terms of speed and battery life though, nothing can beat it as far as I know.

I've been messing around a little bit with Tensorflow Lite using Coral (https://coral.ai/docs/edgetpu/models-intro/)

It allows you to run simple, exportable machine learning models which are super easy to generate from https://teachablemachine.withgoogle.com/

Would be cool to pair with an HB plugin of some kind for a motion sensor or occupancy sensor or even just plain MQTT. Really cool to see how far you are pushing the envelope of HB integration!

**Comment by coast3r** [comment]
Recently installed node-red. Nodes were working before update to 1.3.0 and 1.3.1. Running v0.0.79, installed via the Manage palette menu. PIN is entered and after deployed, the following is displayed in the log:
25 Feb 15:35:44 - [error] [hb-status:86adf5a5.2e176] 437:Can't find device
Does appear to be related to the very recent Homebridge update to 1.3.x. Will continue to look into this.

**Comment by NorthernMan54** [comment]
Double check your device names in each node, am thinking the device name changed for one of your nodes.

and by double check I mean double click each node individual and ensure the name isn’t blank on the device screen

**Comment by coast3r** [comment]
Tried with a clean re-install of the nodes and an empty flow. [Inject] > [HB Status] > [Message]. The PIN has been set in the configuration node. Have also restarted Homebridge and Node-Red. Both are running in Docker. Could have been clearer in my earlier message. It was working with Homebridge 1.2.x. Have been unable to reach Homebridge after 1.3.x upgrade.

**Comment by coast3r** [comment]
Took another look at my Docker settings and changed network_mode to host. This has fixed the issue for me. Perhaps this setting got changed recently while making some other edits to my install. Things are working for me now. Thanks for the advice to double-check everything.

**Comment by NorthernMan54** [comment]
Glad to hear you resolved your issues @coast3r
