### ISSUE TITLE
Don't work with homebridge v1.2.1

### ISSUE THREAD

**Issue by guinmoon** [NorthernMan54/node-red-contrib-homebridge-automation#60]
Sep 15 20:34:08 raspberrypi Node-RED[18868]: 15 Sep 20:34:08 - [error] [hb-status:Bathlight lock] 437:Can't find device Homebridge 0D1C0E:5F:67:3B:0D:1CDefault-ManufacturerBathlight lock00000049
Sep 15 20:34:08 raspberrypi Node-RED[18868]: 15 Sep 20:34:08 - [info] [mqtt-broker:mosquitto] Connected to broker: mqtt://127.0.0.1:1883
Sep 15 20:34:08 raspberrypi Node-RED[18868]: 2020-09-15T17:34:08.859Z hapNodeRed hbStatus Registered: Out Delay - Switch
Sep 15 20:34:08 raspberrypi Node-RED[18868]: 15 Sep 20:34:08 - [error] [hb-status:Out Delay] 437:Can't find device Homebridge 0D1C0E:5F:67:3B:0D:1CDefault-ManufacturerOut Delay00000049
Sep 15 20:34:08 raspberrypi Node-RED[18868]: 2020-09-15T17:34:08.863Z hapNodeRed hbStatus Registered: Bathlight lock - Switch
Sep 15 20:34:08 raspberrypi Node-RED[18868]: 15 Sep 20:34:08 - [error] [hb-status:Bathlight lock] 437:Can't find device Homebridge 0D1C0E:5F:67:3B:0D:1CDefault-ManufacturerBathlight lock00000049
Sep 15 20:34:08 raspberrypi Node-RED[18868]: 2020-09-15T17:34:08.871Z hapNodeRed hbStatus Registered: mono-61e384 - Lightbulb
Sep 15 20:34:08 raspberrypi Node-RED[18868]: 15 Sep 20:34:08 - [error] [hb-status:mono-61e384] 437:Can't find device Homebridge 0D1C0E:5F:67:3B:0D:1CYeeLightmono-61e38400000043
Sep 15 20:34:08 raspberrypi Node-RED[18868]: 2020-09-15T17:34:08.873Z hapNodeRed hbStatus Registered: Kitchen Switch - Switch
Sep 15 20:34:08 raspberrypi Node-RED[18868]: 15 Sep 20:34:08 - [error] [hb-status:Kitchen Switch] 437:Can't find device Homebridge 0D1C0E:5F:67:3B:0D:1CmqttthingKitchen Switch00000049
Sep 15 20:34:08 raspberrypi Node-RED[18868]: 2020-09-15T17:34:08.875Z hapNodeRed hbStatus Registered: Kitchen Switch - Switch
Sep 15 20:34:08 raspberrypi Node-RED[18868]: 15 Sep 20:34:08 - [error] [hb-status:Kitchen Switch] 437:Can't find device Homebridge 0D1C0E:5F:67:3B:0D:1CmqttthingKitchen Switch00000049
Sep 15 20:34:08 raspberrypi Node-RED[18868]: 2020-09-15T17:34:08.878Z hapNodeRed hbStatus Registered: mono-61e384 - Lightbulb
Sep 15 20:34:08 raspberrypi Node-RED[18868]: 15 Sep 20:34:08 - [error] [hb-status:mono-61e384] 437:Can't find device Homebridge 0D1C0E:5F:67:3B:0D:1CYeeLightmono-61e38400000043
Sep 15 20:34:08 raspberrypi Node-RED[18868]: 2020-09-15T17:34:08.880Z hapNodeRed hbStatus Registered: Kitchen Switch - Switch
Sep 15 20:34:08 raspberrypi Node-RED[18868]: 15 Sep 20:34:08 - [error] [hb-status:Kitchen Switch] 437:Can't find device Homebridge 0D1C0E:5F:67:3B:0D:1CmqttthingKitchen Switch00000049
Sep 15 20:34:09 raspberrypi Node-RED[18868]: 15 Sep 20:34:09 - [info] [mqtt-broker:AliceMQTT] Connected to broker: mqtts://aliceghome.site:8883
Sep 15 20:34:09 raspberrypi Node-RED[18868]: 15 Sep 20:34:09 - [error] [hb-control:mono-61e384] Device not found
Sep 15 20:34:17 raspberrypi Node-RED[18868]: 2020-09-15T17:34:17.466Z hapNodeRed evDevices 0
Sep 15 20:34:17 raspberrypi Node-RED[18868]: 2020-09-15T17:34:17.489Z hapNodeRed evDevices 0
Sep 15 20:34:17 raspberrypi Node-RED[18868]: 2020-09-15T17:34:17.510Z hapNodeRed evDevices 0
Sep 15 20:34:21 raspberrypi Node-RED[18868]: 2020-09-15T17:34:21.876Z hapNodeRed evDevices 0

**Comment by NorthernMan54** [comment]
Yeah, homebridge 1.2.1 broke the device naming scheme.  You will need to re-attach your homebridge-automation nodes in the node-red Gui to the devices again.

**Comment by guinmoon** [comment]
Thanks, re-attach works.
