### ISSUE TITLE
Are scheduled triggers and script execution supported?

### ISSUE THREAD

**Issue by cocoabox** [NorthernMan54/node-red-contrib-homebridge-automation#61]
Hi, I have a Roomba which I'd like to activate every Wednesday if it's not a holiday (I curl/awk a calendar ICS file from google) and when there's nobody in the area (occupancy sensor reads negative). Is it possible to do this using node-red-homebridge?

Many thanks

**Comment by NorthernMan54** [comment]
A lot of things are possible with node-red, including this.  it would be a complex flow but do-able, and will take effort as it is unlikely that some has an off the shelf flow you can customize.
