### ISSUE TITLE
Switch doesn't word on homebridge

### ISSUE THREAD

**Issue by edmarts** [NorthernMan54/node-red-contrib-homebridge-automation#62]
Hello! I use Homebridge and Node-Red on my Mac and I'm having problems with automations. When a device passes through the switch or any other node it loses its content and I cannot perform other actions. Am I doing it wrong?

For instance: if I turn on the bedroom light, turn on the fan ... if I turn off the bedroom light, turn off the fan. 

![error](https://user-images.githubusercontent.com/2656908/94052829-daca0c00-fdaf-11ea-9869-ba932b703c98.png)

**Comment by sinowine** [comment]
Do you filled the switch-node with logic?

**Comment by edmarts** [comment]
I filled with two options:
== true
== false

I don't have home assistant, only homebridge.

**Comment by sinowine** [comment]
I use homebridge only too. Can you show how you configured the switch-node?

**Comment by edmarts** [comment]
![switch](https://user-images.githubusercontent.com/2656908/94059064-4ca65380-fdb8-11ea-95b0-d1dfab4b1d98.png)

**Comment by sinowine** [comment]
You have do you use "msg.payload.On" instead of "msg.payload" only ;)

**Comment by edmarts** [comment]
I already tried use msg.payload.On but still does not send the command.
![erro](https://user-images.githubusercontent.com/2656908/94060041-ae1af200-fdb9-11ea-8b4b-632fd92ecd3a.png)
![erro1](https://user-images.githubusercontent.com/2656908/94060154-d7d41900-fdb9-11ea-989d-b0f9e2efed9a.png)
![erro2](https://user-images.githubusercontent.com/2656908/94060186-e4f10800-fdb9-11ea-97f2-d97a918328be.png)

**Comment by sinowine** [comment]
Please try it after you named the switch. I think this could be the problem.

**Comment by edmarts** [comment]
Nothing :'(

**Comment by sinowine** [comment]
Hmm. Deployed after changing?

**Comment by edmarts** [comment]
Yep!

**Comment by NorthernMan54** [comment]
Try adding a debug to listen to the messages coming from the light, and show them on the debug panel.   It is likely a minor issue.

Also that node only emits messages when the device is controlled, so you would need to turn it on or off to trigger a message.

**Comment by edmarts** [comment]
> Try adding a debug node to listen to the messages coming from the light, and show them on the debug panel. It is likely a minor issue.

I've done this. When you add the debug directly to the light it's ok. When the switch is add to the light, nothing happens.
![erro](https://user-images.githubusercontent.com/2656908/94135532-f7128b00-fe39-11ea-8200-992819ed7f2d.png)

> Also that node only emits messages when the device is controlled, so you would need to turn it on or off to trigger a message.

Yep! See the image

**Comment by edmarts** [comment]
I found the "error"!!

I change the "==" signal on switch for "is true/is false" boolean (see the image) and works!

![erro](https://user-images.githubusercontent.com/2656908/94136493-62a92800-fe3b-11ea-8eb2-c904d7491eb5.png)

**Comment by NorthernMan54** [comment]
Awesome
