### ISSUE TITLE
Is there a way to delete an unwanted PIN?

### ISSUE THREAD

**Issue by davidh2075** [NorthernMan54/node-red-contrib-homebridge-automation#63]
I've added to the Pin drop-down list a value I don't want. Is there a way to delete that value?

**Comment by NorthernMan54** [comment]
This is part of node-red


![image](https://user-images.githubusercontent.com/19808920/95470212-83e73980-094e-11eb-8d3e-6b87ea1762e0.png)

**Comment by davidh2075** [comment]
Thank you. I had brought up the config pane and had tried everything I could think of to delete the unused config node.

... except selecting the unused config node and pressing the delete key :-(

Thanks again.
