### ISSUE TITLE
Led strip with the same name

### ISSUE THREAD

**Issue by edmarts** [NorthernMan54/node-red-contrib-homebridge-automation#66]
Hello. I have a problem selecting the LED strips on node-red. All were imported with the same name, ignoring the name given in the homekit, so it is not possible to create automations with them as it only assumes the first in the list as shown in the image.

![led](https://user-images.githubusercontent.com/2656908/97028059-f997fb80-1531-11eb-8a2a-de721a4b35ef.png)

I select a different one but it always goes back to the first one. (I use magic home app/devices)

**Comment by NorthernMan54** [comment]
What plugin are you using for the strip?

For changing the name in the home app, HomeKit does not pass it back homebridge, so I can’t use it for this, the name would need to be adjusted in the plugin.

**Comment by edmarts** [comment]
I use homebridge-magichome-dynamic-platform v1.5.0 on Homebridge

**Comment by NorthernMan54** [comment]
Just looked at the code and he is setting the name from HomeKit back to where node-red should set it.  It may take a few restarts for it to flow thru, but it should.

**Comment by edmarts** [comment]
I've been using it for more than 30 days ... and so far they have the same names ... I've tried changing the name on the homekit app, on the homebridge, but it always stays with the same name on node-red :(

**Comment by NorthernMan54** [comment]
Okay

I have one of those in my parts pile, let me dig it out and see what the challenge is.

**Comment by NorthernMan54** [comment]
Okay, if you update to v0.0.72 it will now use the name from the HomeKit app instead of the default name.  Tks to @Zacknetic for adding this feature to his plugin

**Comment by edmarts** [comment]
Thanks!!!

**Comment by NorthernMan54** [comment]
Fixed ?

**Comment by edmarts** [comment]
Yes!! Thanks!!! :))

**Comment by edmarts** [comment]
Hi, the issue come back! :(

All devices with the same name...
![error](https://user-images.githubusercontent.com/2656908/98953438-738d2600-24db-11eb-98ed-097a081207ac.png)

**Comment by edmarts** [comment]
Hi, the issue come back! :(

All devices with the same name...

**Comment by edmarts** [comment]
And in a magic trick everything went back to normal.... lol (I don't really know what happens but come back ok!!)
