### ISSUE TITLE
No devices on Hoobs hombridge

### ISSUE THREAD

**Issue by cpettis** [NorthernMan54/node-red-contrib-homebridge-automation#72]
No devices show up when I try to configure the HB Event node. I have deleted and re-add the HB-conf, tried the update button, but there are no devices listed in the Device drop-down.

**Comment by NorthernMan54** [comment]
1 - Have you enabled 'Insecure Mode' in your homebridge setup ?

2 - It takes a few minutes to populate the drop down after node-red startup, give it a minute or 2.

3 - Does anything appear in your homebridge logs ?

**Comment by cpettis** [comment]
As far as I can tell from searching google, Hoobs is supposed to start in Insecure mode.

The event node has been in my flow for an hour, nothing in the dropdown box. It does say disconnected below it, and I can't get it to do anything else.

Nothing in the Homebridge logs on Hoobs.

I had an instance of homebridge, and ran it with -I, and it is acting the same as the Hoobs bridge.

**Comment by cpettis** [comment]
It turns out that something was not quite right on node-red in docker on my Synology nas. I installed node red on my pc, and I can connect to my hoobs homebridge server. You can close this issue.
