### ISSUE TITLE
Two Homebridge Instances

### ISSUE THREAD

**Issue by sethfox** [NorthernMan54/node-red-contrib-homebridge-automation#75]
I just added a new homebridge instance (docker container) to my network. Both the old and new instances are running in docker containers on the same host. When I try and interact with the second instance (new) I get an error stating invalid PIN and it references the PIN of the first instance. I am still able to interact with the first instance. 

Node Red is seeing the devices from the second instance, but does not seem to be able to change (turn off or on for example) and devices.

From what I have read this issue may be known, but not clear if this is solved or how I can get my nodered installation in to the right configuration. 

Some Versions:
nodered 1.2.6 - running in docker
node-red-contrib-homebridge-automation 0.0.77 installed tho the pallet shows 0.0.72
homebridge 1.2.4 - Two instances both running in docker. Same hosts as nodered 

Any thoughts on this would be appreciated.

**Comment by NorthernMan54** [comment]
All the pins need to be identical

**Comment by sethfox** [comment]
Thank you! Of course I now see that clearly in the docs for homebridge. Thanks for the reply, seems I should have found that one on my own.

Appreciate the assist, works like a charm now!
