### ISSUE TITLE
Accessory service not available

### ISSUE THREAD

**Issue by horge** [NorthernMan54/node-red-contrib-homebridge-automation#79]
I'm using Eve Thermo (thermostat) in conclusion with homebridge and trying to control the thermostat based on node red rules.

I just followed the installation guide and was able to hook up homebridge. Unfortunately the only service of the accessory which is available in node red is `Bridging State` which only offers the characteristic `Reachable`.

![node-red](https://user-images.githubusercontent.com/4510548/110383789-15bdb480-805d-11eb-9c8e-24406e337a90.jpg)

The other 2 services

* the thermostat control service and
* the battery service

are not properly deployed in node red. Following images of homebridge shows, they are existing and I'm able to modify the temperature.

<img width="522" alt="Bildschirmfoto 2021-03-08 um 22 17 22" src="https://user-images.githubusercontent.com/4510548/110383324-654fb080-805c-11eb-8115-56874884aeb6.png">

I don't entirely know if this is even a problem of this contrib or not - if there is anything that I can provide e.g. logs just let me know.

**Comment by NorthernMan54** [comment]
How did you expose the 'Eve Thermo' to homebridge, homebridge-automation will only work with accessories exposed via homebridge.  Native HomeKit devices are not supported by homebridge-automation.

**Comment by horge** [comment]
There is a homebridge plugin called homebridge-ranger https://github.com/grover/homebridge-ranger, which allows to bridges existing HomeKit BLE accessories.

**Comment by NorthernMan54** [comment]
For this to work you would need to connect to the homebridge instance running Homebridge-ranger, so the settings would need to match that, and then it should be able to extract the details and make the nodes available.  If it still doesn't work, if you could share an accessory dump so I can see what is shared between homebridge and node-red/homebridge-automation and why it can't parse the device.

Details are here for extracting an accessory dump - https://github.com/NorthernMan54/homebridge-alexa#homebridge-accessory-dump

Also node-red may log more details

**Comment by NorthernMan54** [comment]
Tks for the dump, this helps with the issue.  I ran it thru the device parser, and it returned this

```
[
    {
        "homebridge": "parseTest",
        "host": "127.0.0.1",
        "port": 51826,
        "id": "CC:22:3D:E3:CE:30",
        "manufacturer": "Elgato",
        "aid": 4,
        "type": "00000062",
        "name": "Eve Thermo Sichtschutz (6E25)",
        "service": "Bridging State",
        "fullName": "Eve Thermo Sichtschutz (6E25) - Bridging State",
        "sortName": "Eve Thermo Sichtschutz (6E25):Bridging State",
        "uniqueId": "parseTestCC:22:3D:E3:CE:30ElgatoEve Thermo Sichtschutz (6E25)00000062",
        "descriptions": "LinkQuality, Category",
        "characteristics": {
            "4.11": {
                "characteristic": "LinkQuality",
                "iid": 11
            },
            "4.13": {
                "characteristic": "Category",
                "iid": 13
            }
        },
        "getCharacteristics": "4.11,4.13",
        "eventRegisters": [
            {
                "aid": 4,
                "iid": 11,
                "ev": true
            },
            {
                "aid": 4,
                "iid": 13,
                "ev": true
            }
        ]
    }
]
```

And can see the issue

Looking at the data dump, the device parser is expecting the "Description" field to be populated with the description of the characteristic.   And the field being blank is causing the issue.

https://github.com/NorthernMan54/node-red-contrib-homebridge-automation/blob/f714afce28315238880ccd14738f24d0c3958e32/lib/Characteristic.js#L22

Now I need to determine what the fix will be

**Comment by horge** [comment]
I could help myself by manually assigning missing characteristic descriptions, e.g.

https://github.com/NorthernMan54/node-red-contrib-homebridge-automation/blob/f570b3cc72bff3b22804432add6bae457c558f8a/lib/Characteristic.js#L12-L18

becomes

```javascript
function Characteristic(devices, context) {
  // debug("Characteristic", devices);
  this.iid = devices.iid;
  this.type = devices.type.substring(0, 8);
  this.perms = devices.perms;
  this.value = devices.value;
  if (context.aid === 4 && context.service === "Thermostat")
  {
    switch (this.iid)
    {
      case 17:
        devices.description = "Enable";
        break;
      case 19:
        devices.description = "TargetTemperature";
        break;
      default:
        break;
    }
  }
  this.description = devices.description;
```

In node red the characteristics then become e.g. controllable

<img width="508" alt="Bildschirmfoto 2021-03-16 um 19 02 00" src="https://user-images.githubusercontent.com/4510548/111358356-8b8fd480-868a-11eb-960c-2ef8683301b7.png">

Injecting payload to a hb-control then leads to following debug message

```
Payload should be an JSON object containing device characteristics and values, ie {"On":false, "Brightness":0 }
Valid values include: Enable, TargetTemperature
```

and injecting e.g. `TargetTemperature` payload changes the setpoint temperature of the accessory 👍 

I know that this is more or less an ugly hack which works for me, but maybe you can use these information.

**Comment by NorthernMan54** [comment]
Great workaround

What i’m working thru is something similar in approach, and grabbing the values from homebridge itself.

**Comment by NorthernMan54** [comment]
Also the aid and Iid are random and do change

**Comment by NorthernMan54** [comment]
If you update to version v0.0.81 this should now be resolved.

Fix was to go into the homebridge accessory parser and add the descriptions

**Comment by horge** [comment]
Updated to v0.0.81 and the thermostat is (still) working :) Much cleaner fix, thanks a lot!

**Comment by NorthernMan54** [comment]
Tks for confirming
