### ISSUE TITLE
Security System Type not Supported

### ISSUE THREAD

**Issue by NathanAMiller** [NorthernMan54/node-red-contrib-homebridge-automation#9]
"Security System" Accessory not showing up in accessories list.

You can create a fake "Security System Accessory" using this package:
https://www.npmjs.com/package/homebridge-automation-switches

**Comment by NorthernMan54** [comment]
Can you share an homebridge accessory dump from your homebridge instance with the “Security System”.  Want to see why it isn’t listed

https://github.com/NorthernMan54/homebridge-alexa#homebridge-accessory-dump

**Comment by NathanAMiller** [comment]
My bad. It seems the list was not updated. After couple of days the switch showed up in the list 👍🏽

**Comment by NathanAMiller** [comment]
Ok. This time i'm sure that its not cache. It seems that "Television" accessories is not support. I have in Homebridge UI but not in NodeRed list.

<img width="310" alt="Screenshot 2019-06-12 18 23 46" src="https://user-images.githubusercontent.com/51482347/59359625-ecff7280-8d43-11e9-957b-930f8bc4d1c6.png">


`{  
   "accessories":[  
    









      {  
         "aid":12,
         "services":[  
            {  
               "iid":1,
               "type":"0000003E-0000-1000-8000-0026BB765291",
               "characteristics":[  
                  {  
                     "iid":2,
                     "type":"00000014-0000-1000-8000-0026BB765291",
                     "perms":[  
                        "pw"
                     ],
                     "format":"bool",
                     "description":"Identify"
                  },
                  {  
                     "iid":3,
                     "type":"00000020-0000-1000-8000-0026BB765291",
                     "perms":[  
                        "pr"
                     ],
                     "format":"string",
                     "value":"LG Electronics Inc.",
                     "description":"Manufacturer"
                  },
                  {  
                     "iid":4,
                     "type":"00000021-0000-1000-8000-0026BB765291",
                     "perms":[  
                        "pr"
                     ],
                     "format":"string",
                     "value":"49SJ800V-TA",
                     "description":"Model"
                  },
                  {  
                     "iid":5,
                     "type":"00000023-0000-1000-8000-0026BB765291",
                     "perms":[  
                        "pr"
                     ],
                     "format":"string",
                     "value":"LG TV",
                     "description":"Name"
                  },
                  {  
                     "iid":6,
                     "type":"00000030-0000-1000-8000-0026BB765291",
                     "perms":[  
                        "pr"
                     ],
                     "format":"string",
                     "value":"94:6A:B0:08:C6:95",
                     "description":"Serial Number"
                  },
                  {  
                     "iid":7,
                     "type":"00000052-0000-1000-8000-0026BB765291",
                     "perms":[  
                        "pr"
                     ],
                     "format":"string",
                     "value":"1.6.1",
                     "description":"Firmware Revision"
                  }
               ],
               "primary":false,
               "hidden":false
            },










            {  
               "iid":8,
               "type":"000000D8-0000-1000-8000-0026BB765291",
               "characteristics":[  
                  {  
                     "iid":9,
                     "type":"00000023-0000-1000-8000-0026BB765291",
                     "perms":[  
                        "pr"
                     ],
                     "format":"string",
                     "value":"LG TV",
                     "description":"Name"
                  },
                  {  
                     "iid":10,
                     "type":"000000B0-0000-1000-8000-0026BB765291",
                     "perms":[  
                        "pr",
                        "pw",
                        "ev"
                     ],
                     "format":"uint8",
                     "value":1,
                     "description":"Active",
                     "valid-values":[  
                        0,
                        1
                     ],
                     "maxValue":1,
                     "minValue":0
                  },
                  {  
                     "iid":11,
                     "type":"000000E7-0000-1000-8000-0026BB765291",
                     "perms":[  
                        "pr",
                        "pw",
                        "ev"
                     ],
                     "format":"uint32",
                     "value":0,
                     "description":"Active Identifier"
                  },
                  {  
                     "iid":12,
                     "type":"000000E3-0000-1000-8000-0026BB765291",
                     "perms":[  
                        "pr",
                        "pw",
                        "ev"
                     ],
                     "format":"string",
                     "value":"LG TV",
                     "description":"Configured Name"
                  },
                  {  
                     "iid":13,
                     "type":"000000E8-0000-1000-8000-0026BB765291",
                     "perms":[  
                        "pr",
                        "ev"
                     ],
                     "format":"uint8",
                     "value":1,
                     "description":"Sleep Discovery Mode",
                     "valid-values":[  
                        0,
                        1
                     ],
                     "maxValue":1,
                     "minValue":0
                  },
                  {  
                     "iid":14,
                     "type":"000000E1-0000-1000-8000-0026BB765291",
                     "perms":[  
                        "pw"
                     ],
                     "format":"uint8",
                     "description":"Remote Key",
                     "valid-values":[  
                        0,
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16
                     ],
                     "maxValue":16,
                     "minValue":0
                  },
                  {  
                     "iid":15,
                     "type":"000000DF-0000-1000-8000-0026BB765291",
                     "perms":[  
                        "pw"
                     ],
                     "format":"uint8",
                     "description":"Power Mode Selection",
                     "valid-values":[  
                        0,
                        1
                     ],
                     "maxValue":1,
                     "minValue":0
                  }
               ],
               "primary":false,
               "hidden":false,
               "linked":[  
                  16,
                  23,
                  30
               ]
            },













            {  
               "iid":16,
               "type":"00000113-0000-1000-8000-0026BB765291",
               "characteristics":[  
                  {  
                     "iid":17,
                     "type":"00000023-0000-1000-8000-0026BB765291",
                     "perms":[  
                        "pr"
                     ],
                     "format":"string",
                     "value":"LG TV Volume",
                     "description":"Name"
                  },
                  {  
                     "iid":18,
                     "type":"0000011A-0000-1000-8000-0026BB765291",
                     "perms":[  
                        "pr",
                        "pw",
                        "ev"
                     ],
                     "format":"bool",
                     "value":false,
                     "description":"Mute"
                  },
                  {  
                     "iid":19,
                     "type":"000000B0-0000-1000-8000-0026BB765291",
                     "perms":[  
                        "pr",
                        "pw",
                        "ev"
                     ],
                     "format":"uint8",
                     "value":1,
                     "description":"Active",
                     "valid-values":[  
                        0,
                        1
                     ],
                     "maxValue":1,
                     "minValue":0
                  },
                  {  
                     "iid":20,
                     "type":"000000E9-0000-1000-8000-0026BB765291",
                     "perms":[  
                        "pr",
                        "ev"
                     ],
                     "format":"uint8",
                     "value":3,
                     "description":"Volume Control Type",
                     "valid-values":[  
                        0,
                        1,
                        2,
                        3
                     ],
                     "maxValue":3,
                     "minValue":0
                  },
                  {  
                     "iid":21,
                     "type":"000000EA-0000-1000-8000-0026BB765291",
                     "perms":[  
                        "pw"
                     ],
                     "format":"uint8",
                     "description":"Volume Selector",
                     "valid-values":[  
                        0,
                        1
                     ],
                     "maxValue":1,
                     "minValue":0
                  },
                  {  
                     "iid":22,
                     "type":"00000119-0000-1000-8000-0026BB765291",
                     "perms":[  
                        "pr",
                        "pw",
                        "ev"
                     ],
                     "format":"uint8",
                     "value":0,
                     "description":"Volume",
                     "unit":"percentage",
                     "maxValue":100,
                     "minValue":0,
                     "minStep":1
                  }
               ],
               "primary":false,
               "hidden":false
            },












            {  
               "iid":23,
               "type":"000000D9-0000-1000-8000-0026BB765291",
               "characteristics":[  
                  {  
                     "iid":24,
                     "type":"00000023-0000-1000-8000-0026BB765291",
                     "perms":[  
                        "pr"
                     ],
                     "format":"string",
                     "value":"com.webos.app.livetv",
                     "description":"Name"
                  },
                  {  
                     "iid":25,
                     "type":"000000E3-0000-1000-8000-0026BB765291",
                     "perms":[  
                        "pr",
                        "pw",
                        "ev"
                     ],
                     "format":"string",
                     "value":"Live TV",
                     "description":"Configured Name"
                  },
                  {  
                     "iid":26,
                     "type":"000000DB-0000-1000-8000-0026BB765291",
                     "perms":[  
                        "pr",
                        "ev"
                     ],
                     "format":"uint8",
                     "value":10,
                     "description":"Input Source Type",
                     "valid-values":[  
                        0,
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10
                     ],
                     "maxValue":10,
                     "minValue":0
                  },
                  {  
                     "iid":27,
                     "type":"000000D6-0000-1000-8000-0026BB765291",
                     "perms":[  
                        "pr",
                        "pw",
                        "ev"
                     ],
                     "format":"uint8",
                     "value":1,
                     "description":"Is Configured",
                     "valid-values":[  
                        0,
                        1
                     ],
                     "maxValue":1,
                     "minValue":0
                  },
                  {  
                     "iid":28,
                     "type":"00000135-0000-1000-8000-0026BB765291",
                     "perms":[  
                        "pr",
                        "ev"
                     ],
                     "format":"uint8",
                     "value":0,
                     "description":"Current Visibility State",
                     "valid-values":[  
                        0,
                        1,
                        2,
                        3
                     ],
                     "maxValue":3,
                     "minValue":0
                  },
                  {  
                     "iid":29,
                     "type":"000000E6-0000-1000-8000-0026BB765291",
                     "perms":[  
                        "pr"
                     ],
                     "format":"uint32",
                     "value":0,
                     "description":"Identifier",
                     "minValue":0,
                     "minStep":1
                  }
               ],
               "primary":false,
               "hidden":false
            },














            {  
               "iid":30,
               "type":"000000D9-0000-1000-8000-0026BB765291",
               "characteristics":[  
                  {  
                     "iid":31,
                     "type":"00000023-0000-1000-8000-0026BB765291",
                     "perms":[  
                        "pr"
                     ],
                     "format":"string",
                     "value":"com.webos.app.hdmi1",
                     "description":"Name"
                  },
                  {  
                     "iid":32,
                     "type":"000000E3-0000-1000-8000-0026BB765291",
                     "perms":[  
                        "pr",
                        "pw",
                        "ev"
                     ],
                     "format":"string",
                     "value":"Apple TV",
                     "description":"Configured Name"
                  },
                  {  
                     "iid":33,
                     "type":"000000DB-0000-1000-8000-0026BB765291",
                     "perms":[  
                        "pr",
                        "ev"
                     ],
                     "format":"uint8",
                     "value":10,
                     "description":"Input Source Type",
                     "valid-values":[  
                        0,
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10
                     ],
                     "maxValue":10,
                     "minValue":0
                  },
                  {  
                     "iid":34,
                     "type":"000000D6-0000-1000-8000-0026BB765291",
                     "perms":[  
                        "pr",
                        "pw",
                        "ev"
                     ],
                     "format":"uint8",
                     "value":1,
                     "description":"Is Configured",
                     "valid-values":[  
                        0,
                        1
                     ],
                     "maxValue":1,
                     "minValue":0
                  },
                  {  
                     "iid":35,
                     "type":"00000135-0000-1000-8000-0026BB765291",
                     "perms":[  
                        "pr",
                        "ev"
                     ],
                     "format":"uint8",
                     "value":0,
                     "description":"Current Visibility State",
                     "valid-values":[  
                        0,
                        1,
                        2,
                        3
                     ],
                     "maxValue":3,
                     "minValue":0
                  },
                  {  
                     "iid":36,
                     "type":"000000E6-0000-1000-8000-0026BB765291",
                     "perms":[  
                        "pr"
                     ],
                     "format":"uint32",
                     "value":1,
                     "description":"Identifier",
                     "minValue":0,
                     "minStep":1
                  }
               ],
               "primary":false,
               "hidden":false
            },











            {  
               "iid":37,
               "type":"00000043-0000-1000-8000-0026BB765291",
               "characteristics":[  
                  {  
                     "iid":38,
                     "type":"00000023-0000-1000-8000-0026BB765291",
                     "perms":[  
                        "pr"
                     ],
                     "format":"string",
                     "value":"LG TV Volume",
                     "description":"Name"
                  },
                  {  
                     "iid":39,
                     "type":"00000025-0000-1000-8000-0026BB765291",
                     "perms":[  
                        "pr",
                        "pw",
                        "ev"
                     ],
                     "format":"bool",
                     "value":true,
                     "description":"On"
                  },
                  {  
                     "iid":40,
                     "type":"00000008-0000-1000-8000-0026BB765291",
                     "perms":[  
                        "pr",
                        "pw",
                        "ev"
                     ],
                     "format":"int",
                     "value":7,
                     "description":"Brightness",
                     "unit":"percentage",
                     "maxValue":100,
                     "minValue":0,
                     "minStep":1
                  }
               ],
               "primary":false,
               "hidden":false
            }
         ]
      }



   ]
}`

**Comment by NorthernMan54** [comment]
I just ran it thru the accessory parser and it returned the TV accessory.  One thing to keep in mind is that this node does not about accessory types.  It just parses them into “nodes”.

This is what the parser should pass into Node-Red, 2 nodes, one called "LG TV Volume - Lightbulb" and the other "LG TV Volume - Speaker"

```
[
    {
        "homebridge": "parseTest",
        "host": "127.0.0.1",
        "port": 51826,
        "id": "CC:22:3D:E3:CE:30",
        "manufacturer": "LG Electronics Inc.",
        "aid": 12,
        "type": "00000043",
        "name": "LG TV Volume",
        "service": "Lightbulb",
        "fullName": "LG TV Volume - Lightbulb",
        "sortName": "LG TV Volume:Lightbulb",
        "uniqueId": "parseTestCC:22:3D:E3:CE:30LG Electronics Inc.LG TV Volume00000043",
        "descriptions": "On,Brightness",
        "characteristics": {
            "12.39": {
                "characteristic": "On",
                "iid": 39
            },
            "12.40": {
                "characteristic": "Brightness",
                "iid": 40
            }
        },
        "getCharacteristics": "12.39,12.40",
        "eventRegisters": [
            {
                "aid": 12,
                "iid": 39,
                "ev": true
            },
            {
                "aid": 12,
                "iid": 40,
                "ev": true
            }
        ]
    },
    {
        "homebridge": "parseTest",
        "host": "127.0.0.1",
        "port": 51826,
        "id": "CC:22:3D:E3:CE:30",
        "manufacturer": "LG Electronics Inc.",
        "aid": 12,
        "type": "00000113",
        "name": "LG TV Volume",
        "service": "Speaker",
        "fullName": "LG TV Volume - Speaker",
        "sortName": "LG TV Volume:Speaker",
        "uniqueId": "parseTestCC:22:3D:E3:CE:30LG Electronics Inc.LG TV Volume00000113",
        "descriptions": "Mute,Active,Volume Control Type,Volume",
        "characteristics": {
            "12.18": {
                "characteristic": "Mute",
                "iid": 18
            },
            "12.19": {
                "characteristic": "Active",
                "iid": 19
            },
            "12.20": {
                "characteristic": "VolumeControlType",
                "iid": 20
            },
            "12.22": {
                "characteristic": "Volume",
                "iid": 22
            }
        },
        "getCharacteristics": "12.18,12.19,12.20,12.22",
        "eventRegisters": [
            {
                "aid": 12,
                "iid": 18,
                "ev": true
            },
            {
                "aid": 12,
                "iid": 19,
                "ev": true
            },
            {
                "aid": 12,
                "iid": 20,
                "ev": true
            },
            {
                "aid": 12,
                "iid": 22,
                "ev": true
            }
        ]
    }
]
```

**Comment by rcarmo** [comment]
I just landed here because I'm also trying to figure out how to get a "TV On" event from the exact same `homebridge` plugin, and was wondering how to get that in Node-RED.

Just FYI, relying on the volume node doesn't work if (like me) you route audio through the optical out on the TV - that disables the volume control.

Any ideas on how to check the status of the TV via HomeKit? The alternative is to resort to another Node-RED library, but that kind o negates the use of this one...

**Comment by NathanAMiller** [comment]
Please check my codes. I have "LG TV Volume - Lightbulb" and "LG TV Volume - Speaker" as well. But these accessories is just for setting and changing volume. There should be some more accessories to control the main TV. Turing it ON/OFF changing source and channel and more.

By the way... did you update Homebridge UI?

**Comment by NorthernMan54** [comment]
I added the missing "Input Source" Service, update to the latest and try again

Looking at the nodes etc, and a TV is quite complex and may take some experimentation to get it to work the way you want

```
[
    {
        "homebridge": "parseTest",
        "host": "127.0.0.1",
        "port": 51826,
        "id": "CC:22:3D:E3:CE:30",
        "manufacturer": "LG Electronics Inc.",
        "aid": 12,
        "type": "00000043",
        "name": "LG TV Volume",
        "service": "Lightbulb",
        "fullName": "LG TV Volume - Lightbulb",
        "sortName": "LG TV Volume:Lightbulb",
        "uniqueId": "parseTestCC:22:3D:E3:CE:30LG Electronics Inc.LG TV Volume00000043",
        "descriptions": "On,Brightness",
        "characteristics": {
            "12.39": {
                "characteristic": "On",
                "iid": 39
            },
            "12.40": {
                "characteristic": "Brightness",
                "iid": 40
            }
        },
        "getCharacteristics": "12.39,12.40",
        "eventRegisters": [
            {
                "aid": 12,
                "iid": 39,
                "ev": true
            },
            {
                "aid": 12,
                "iid": 40,
                "ev": true
            }
        ]
    },
    {
        "homebridge": "parseTest",
        "host": "127.0.0.1",
        "port": 51826,
        "id": "CC:22:3D:E3:CE:30",
        "manufacturer": "LG Electronics Inc.",
        "aid": 12,
        "type": "00000113",
        "name": "LG TV Volume",
        "service": "Speaker",
        "fullName": "LG TV Volume - Speaker",
        "sortName": "LG TV Volume:Speaker",
        "uniqueId": "parseTestCC:22:3D:E3:CE:30LG Electronics Inc.LG TV Volume00000113",
        "descriptions": "Mute,Active,Volume Control Type,Volume",
        "characteristics": {
            "12.18": {
                "characteristic": "Mute",
                "iid": 18
            },
            "12.19": {
                "characteristic": "Active",
                "iid": 19
            },
            "12.20": {
                "characteristic": "VolumeControlType",
                "iid": 20
            },
            "12.22": {
                "characteristic": "Volume",
                "iid": 22
            }
        },
        "getCharacteristics": "12.18,12.19,12.20,12.22",
        "eventRegisters": [
            {
                "aid": 12,
                "iid": 18,
                "ev": true
            },
            {
                "aid": 12,
                "iid": 19,
                "ev": true
            },
            {
                "aid": 12,
                "iid": 20,
                "ev": true
            },
            {
                "aid": 12,
                "iid": 22,
                "ev": true
            }
        ]
    },
    {
        "homebridge": "parseTest",
        "host": "127.0.0.1",
        "port": 51826,
        "id": "CC:22:3D:E3:CE:30",
        "manufacturer": "LG Electronics Inc.",
        "aid": 12,
        "type": "000000D9",
        "name": "com.webos.app.hdmi1",
        "service": "Input Source",
        "fullName": "com.webos.app.hdmi1 - Input Source",
        "sortName": "com.webos.app.hdmi1:Input Source",
        "uniqueId": "parseTestCC:22:3D:E3:CE:30LG Electronics Inc.com.webos.app.hdmi1000000D9",
        "descriptions": "Configured Name,Input Source Type,Is Configured,Current Visibility State",
        "characteristics": {
            "12.32": {
                "characteristic": "ConfiguredName",
                "iid": 32
            },
            "12.33": {
                "characteristic": "InputSourceType",
                "iid": 33
            },
            "12.34": {
                "characteristic": "IsConfigured",
                "iid": 34
            },
            "12.35": {
                "characteristic": "CurrentVisibilityState",
                "iid": 35
            }
        },
        "getCharacteristics": "12.32,12.33,12.34,12.35",
        "eventRegisters": [
            {
                "aid": 12,
                "iid": 32,
                "ev": true
            },
            {
                "aid": 12,
                "iid": 33,
                "ev": true
            },
            {
                "aid": 12,
                "iid": 34,
                "ev": true
            },
            {
                "aid": 12,
                "iid": 35,
                "ev": true
            }
        ]
    },
    {
        "homebridge": "parseTest",
        "host": "127.0.0.1",
        "port": 51826,
        "id": "CC:22:3D:E3:CE:30",
        "manufacturer": "LG Electronics Inc.",
        "aid": 12,
        "type": "000000D9",
        "name": "com.webos.app.livetv",
        "service": "Input Source",
        "fullName": "com.webos.app.livetv - Input Source",
        "sortName": "com.webos.app.livetv:Input Source",
        "uniqueId": "parseTestCC:22:3D:E3:CE:30LG Electronics Inc.com.webos.app.livetv000000D9",
        "descriptions": "Configured Name,Input Source Type,Is Configured,Current Visibility State",
        "characteristics": {
            "12.25": {
                "characteristic": "ConfiguredName",
                "iid": 25
            },
            "12.26": {
                "characteristic": "InputSourceType",
                "iid": 26
            },
            "12.27": {
                "characteristic": "IsConfigured",
                "iid": 27
            },
            "12.28": {
                "characteristic": "CurrentVisibilityState",
                "iid": 28
            }
        },
        "getCharacteristics": "12.25,12.26,12.27,12.28",
        "eventRegisters": [
            {
                "aid": 12,
                "iid": 25,
                "ev": true
            },
            {
                "aid": 12,
                "iid": 26,
                "ev": true
            },
            {
                "aid": 12,
                "iid": 27,
                "ev": true
            },
            {
                "aid": 12,
                "iid": 28,
                "ev": true
            }
        ]
    }
]
```

**Comment by NathanAMiller** [comment]
Thanks. I'll test it on new version.

I think there should be another accessory type too. To turn On/Off the TV. Like this :

`
        {  
           "iid":8,
           "type":"000000D8-0000-1000-8000-0026BB765291",
           "characteristics":[  
              {  
                 "iid":9,
                 "type":"00000023-0000-1000-8000-0026BB765291",
                 "perms":[  
                    "pr"
                 ],
                 "format":"string",
                 "value":"LG TV",
                 "description":"Name"
              },
              {  
                 "iid":10,
                 "type":"000000B0-0000-1000-8000-0026BB765291",
                 "perms":[  
                    "pr",
                    "pw",
                    "ev"
                 ],
                 "format":"uint8",
                 "value":1,
                 "description":"Active",
                 "valid-values":[  
                    0,
                    1
                 ],
                 "maxValue":1,
                 "minValue":0
              },
              {  
                 "iid":11,
                 "type":"000000E7-0000-1000-8000-0026BB765291",
                 "perms":[  
                    "pr",
                    "pw",
                    "ev"
                 ],
                 "format":"uint32",
                 "value":0,
                 "description":"Active Identifier"
              },
              {  
                 "iid":12,
                 "type":"000000E3-0000-1000-8000-0026BB765291",
                 "perms":[  
                    "pr",
                    "pw",
                    "ev"
                 ],
                 "format":"string",
                 "value":"LG TV",
                 "description":"Configured Name"
              },
              {  
                 "iid":13,
                 "type":"000000E8-0000-1000-8000-0026BB765291",
                 "perms":[  
                    "pr",
                    "ev"
                 ],
                 "format":"uint8",
                 "value":1,
                 "description":"Sleep Discovery Mode",
                 "valid-values":[  
                    0,
                    1
                 ],
                 "maxValue":1,
                 "minValue":0
              },
              {  
                 "iid":14,
                 "type":"000000E1-0000-1000-8000-0026BB765291",
                 "perms":[  
                    "pw"
                 ],
                 "format":"uint8",
                 "description":"Remote Key",
                 "valid-values":[  
                    0,
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9,
                    10,
                    11,
                    12,
                    13,
                    14,
                    15,
                    16
                 ],
                 "maxValue":16,
                 "minValue":0
              },
              {  
                 "iid":15,
                 "type":"000000DF-0000-1000-8000-0026BB765291",
                 "perms":[  
                    "pw"
                 ],
                 "format":"uint8",
                 "description":"Power Mode Selection",
                 "valid-values":[  
                    0,
                    1
                 ],
                 "maxValue":1,
                 "minValue":0
              }
           ],
           "primary":false,
           "hidden":false,
           "linked":[  
              16,
              23,
              30
           ]
        },
`

**Comment by rcarmo** [comment]
I concur. Not being able to see if the TV is on or off is the most important part.

**Comment by NorthernMan54** [comment]
I just added the remaining Television service, and it now parses like this for Node-Red, please update and try again

```
[
    {
        "homebridge": "parseTest",
        "host": "127.0.0.1",
        "port": 51826,
        "id": "CC:22:3D:E3:CE:30",
        "manufacturer": "LG Electronics Inc.",
        "aid": 12,
        "type": "00000043",
        "name": "LG TV Volume",
        "service": "Lightbulb",
        "fullName": "LG TV Volume - Lightbulb",
        "sortName": "LG TV Volume:Lightbulb",
        "uniqueId": "parseTestCC:22:3D:E3:CE:30LG Electronics Inc.LG TV Volume00000043",
        "descriptions": "On,Brightness",
        "characteristics": {
            "12.39": {
                "characteristic": "On",
                "iid": 39
            },
            "12.40": {
                "characteristic": "Brightness",
                "iid": 40
            }
        },
        "getCharacteristics": "12.39,12.40",
        "eventRegisters": [
            {
                "aid": 12,
                "iid": 39,
                "ev": true
            },
            {
                "aid": 12,
                "iid": 40,
                "ev": true
            }
        ]
    },
    {
        "homebridge": "parseTest",
        "host": "127.0.0.1",
        "port": 51826,
        "id": "CC:22:3D:E3:CE:30",
        "manufacturer": "LG Electronics Inc.",
        "aid": 12,
        "type": "00000113",
        "name": "LG TV Volume",
        "service": "Speaker",
        "fullName": "LG TV Volume - Speaker",
        "sortName": "LG TV Volume:Speaker",
        "uniqueId": "parseTestCC:22:3D:E3:CE:30LG Electronics Inc.LG TV Volume00000113",
        "descriptions": "Mute,Active,Volume Control Type,Volume",
        "characteristics": {
            "12.18": {
                "characteristic": "Mute",
                "iid": 18
            },
            "12.19": {
                "characteristic": "Active",
                "iid": 19
            },
            "12.20": {
                "characteristic": "VolumeControlType",
                "iid": 20
            },
            "12.22": {
                "characteristic": "Volume",
                "iid": 22
            }
        },
        "getCharacteristics": "12.18,12.19,12.20,12.22",
        "eventRegisters": [
            {
                "aid": 12,
                "iid": 18,
                "ev": true
            },
            {
                "aid": 12,
                "iid": 19,
                "ev": true
            },
            {
                "aid": 12,
                "iid": 20,
                "ev": true
            },
            {
                "aid": 12,
                "iid": 22,
                "ev": true
            }
        ]
    },
    {
        "homebridge": "parseTest",
        "host": "127.0.0.1",
        "port": 51826,
        "id": "CC:22:3D:E3:CE:30",
        "manufacturer": "LG Electronics Inc.",
        "aid": 12,
        "type": "000000D8",
        "name": "LG TV",
        "service": "Television",
        "fullName": "LG TV - Television",
        "sortName": "LG TV:Television",
        "uniqueId": "parseTestCC:22:3D:E3:CE:30LG Electronics Inc.LG TV000000D8",
        "descriptions": "Active,Active Identifier,Configured Name,Sleep Discovery Mode",
        "characteristics": {
            "12.10": {
                "characteristic": "Active",
                "iid": 10
            },
            "12.11": {
                "characteristic": "ActiveIdentifier",
                "iid": 11
            },
            "12.12": {
                "characteristic": "ConfiguredName",
                "iid": 12
            },
            "12.13": {
                "characteristic": "SleepDiscoveryMode",
                "iid": 13
            }
        },
        "getCharacteristics": "12.10,12.11,12.12,12.13",
        "eventRegisters": [
            {
                "aid": 12,
                "iid": 10,
                "ev": true
            },
            {
                "aid": 12,
                "iid": 11,
                "ev": true
            },
            {
                "aid": 12,
                "iid": 12,
                "ev": true
            },
            {
                "aid": 12,
                "iid": 13,
                "ev": true
            }
        ]
    },
    {
        "homebridge": "parseTest",
        "host": "127.0.0.1",
        "port": 51826,
        "id": "CC:22:3D:E3:CE:30",
        "manufacturer": "LG Electronics Inc.",
        "aid": 12,
        "type": "000000D9",
        "name": "com.webos.app.hdmi1",
        "service": "Input Source",
        "fullName": "com.webos.app.hdmi1 - Input Source",
        "sortName": "com.webos.app.hdmi1:Input Source",
        "uniqueId": "parseTestCC:22:3D:E3:CE:30LG Electronics Inc.com.webos.app.hdmi1000000D9",
        "descriptions": "Configured Name,Input Source Type,Is Configured,Current Visibility State",
        "characteristics": {
            "12.32": {
                "characteristic": "ConfiguredName",
                "iid": 32
            },
            "12.33": {
                "characteristic": "InputSourceType",
                "iid": 33
            },
            "12.34": {
                "characteristic": "IsConfigured",
                "iid": 34
            },
            "12.35": {
                "characteristic": "CurrentVisibilityState",
                "iid": 35
            }
        },
        "getCharacteristics": "12.32,12.33,12.34,12.35",
        "eventRegisters": [
            {
                "aid": 12,
                "iid": 32,
                "ev": true
            },
            {
                "aid": 12,
                "iid": 33,
                "ev": true
            },
            {
                "aid": 12,
                "iid": 34,
                "ev": true
            },
            {
                "aid": 12,
                "iid": 35,
                "ev": true
            }
        ]
    },
    {
        "homebridge": "parseTest",
        "host": "127.0.0.1",
        "port": 51826,
        "id": "CC:22:3D:E3:CE:30",
        "manufacturer": "LG Electronics Inc.",
        "aid": 12,
        "type": "000000D9",
        "name": "com.webos.app.livetv",
        "service": "Input Source",
        "fullName": "com.webos.app.livetv - Input Source",
        "sortName": "com.webos.app.livetv:Input Source",
        "uniqueId": "parseTestCC:22:3D:E3:CE:30LG Electronics Inc.com.webos.app.livetv000000D9",
        "descriptions": "Configured Name,Input Source Type,Is Configured,Current Visibility State",
        "characteristics": {
            "12.25": {
                "characteristic": "ConfiguredName",
                "iid": 25
            },
            "12.26": {
                "characteristic": "InputSourceType",
                "iid": 26
            },
            "12.27": {
                "characteristic": "IsConfigured",
                "iid": 27
            },
            "12.28": {
                "characteristic": "CurrentVisibilityState",
                "iid": 28
            }
        },
        "getCharacteristics": "12.25,12.26,12.27,12.28",
        "eventRegisters": [
            {
                "aid": 12,
                "iid": 25,
                "ev": true
            },
            {
                "aid": 12,
                "iid": 26,
                "ev": true
            },
            {
                "aid": 12,
                "iid": 27,
                "ev": true
            },
            {
                "aid": 12,
                "iid": 28,
                "ev": true
            }
        ]
    }
]
```

**Comment by NathanAMiller** [comment]
So far, So good. Thank you.

Now I have some new accessories in Node-Red. I have a single accessory for each TV and i can turn it ON and OFF by changing "Active" variable to "0" & "1". (Its not like other accessories that works with On: true / false ).

But I'm not able the work with Input Sources. Now I have a separate accessory for each Input Source on my TV in Node-Red. But i'm unable to active any of them on the TV. I'm not sure which key/variable should i work with in order to active the input source. I have these parameters on each Input source

`
ConfiguredName: "Live TV"
InputSourceType: 10
IsConfigured: 1
CurrentVisibilityState: 0
Identifier: 0
`

**Comment by NorthernMan54** [comment]
Try creating an hb-event node for a couple of inputs and hook a debug node up to it.  Then look and see what is output when you select the input.  That should give you a clue

**Comment by NathanAMiller** [comment]
I did it like this :

<img width="642" alt="Screenshot 2019-06-23 23 23 44" src="https://user-images.githubusercontent.com/51482347/59980642-fc1cd500-960d-11e9-9181-5b60e4e818b3.png">

and change the source on the TV many times and No output at all. Am i did it something wrong?

**Comment by NorthernMan54** [comment]
Are those "Input Source" devices?

Please keep in mind that I don't have a HomeBridge compatible TV in my setup so this is a bit of hunt and peck to get going the first time.

**Comment by NathanAMiller** [comment]
First one is an "Input Source" and the second one is the main TV accessory

**Comment by NorthernMan54** [comment]
I'm thinking if you use the home app, and change to input source to "HDMI Switch" it should output something.

**Comment by NathanAMiller** [comment]
I tried many times changing sources on TV trough Homekit and remote control.  I have some outputs on "TV" accessory but nothing on "Input Sources" accessories.

<img width="306" alt="Screenshot 2019-07-04 19 50 22" src="https://user-images.githubusercontent.com/51482347/60676896-4ebf8200-9e95-11e9-9ee8-90841b4e1d0b.png">

<img width="403" alt="Screenshot 2019-07-04 19 33 13" src="https://user-images.githubusercontent.com/51482347/60676897-4ebf8200-9e95-11e9-8717-9c7fb671592e.png">

**Comment by NorthernMan54** [comment]
Do you think you could convince my wife that we need a new TV 📺 so I can directly troubleshoot this?

Another thought is watch what is sent between the Home app and the plugin.  Then map that to the nodes ( this would require running debug mode against the lg plugin, and collecting log events during an input switch )

**Comment by NathanAMiller** [comment]
The first solution seems to be more practical :D
