### ISSUE TITLE
Outputs on hb - control node?

### ISSUE THREAD

**Issue by Lorccan** [NorthernMan54/node-red-contrib-homebridge-automation#93]
What is the purpose of the Outputs option on an 'hb - control' node?

How does a message get directed to a specific one (where there is more than one)?

**Comment by NorthernMan54** [comment]
The outputs on a control node are the special use case around camera's and collecting a snapshot image.

**Comment by Lorccan** [comment]
Ah! OK.  I’m not using cameras so it’s not applicable to me.  Thanks for the quick reply!

**Comment by NorthernMan54** [comment]
No problem, was just looking at something else and it was a quick answer
